/**
 * Reviewed refresh workflow tests.
 *
 * Coverage:
 *   - offline generation from committed snapshots
 *   - mocked live refresh writes snapshots and reports refreshed sources
 *   - unrefreshable sources (OpenAI) are skipped with an honest note
 *   - missing env vars surface as errors, not unauthenticated fetches
 *   - reviewable file diffs (before/after/changed)
 *   - write=false never mutates disk
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest"
import { existsSync, mkdirSync, rmSync, writeFileSync, readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import {
  reviewedRefresh,
  refreshSources,
  OPENAI_LLM_SOURCE,
  defineGenerator,
  type GeneratedFiles,
  type GeneratorContext,
  type RefreshableSource,
} from "../index.js"

const HERE = dirname(fileURLToPath(import.meta.url))
const PKG_DIR = join(HERE, "..", "..")
const TMP_DIR = join(PKG_DIR, ".test-tmp-refresh")
const REL_OUT = "packages/catalog-sync/.test-tmp-refresh/refresh.generated.ts"
const ABS_OUT = join(TMP_DIR, "refresh.generated.ts")

function mockGen(): ReturnType<typeof defineGenerator> {
  return defineGenerator({
    name: "mock:refresh",
    modality: "llm",
    sources: [],
    async generate(_ctx: GeneratorContext): Promise<GeneratedFiles> {
      return {
        [REL_OUT]:
          "// AUTO-GENERATED by refresh workflow test.\n" +
          'export const REFRESHED = "yes" as const\n',
      }
    },
  })
}

function mockFetch(response: unknown): typeof fetch {
  return async () =>
    ({
      ok: true,
      status: 200,
      statusText: "OK",
      text: async () => JSON.stringify(response),
    } as Response)
}
const MOCK_SNAPSHOT = join(PKG_DIR, "snapshots", "mock-source.json")

describe("reviewedRefresh", () => {
  beforeEach(() => {
    mkdirSync(TMP_DIR, { recursive: true })
  })
  afterEach(() => {
    rmSync(TMP_DIR, { recursive: true, force: true })
    if (existsSync(MOCK_SNAPSHOT)) rmSync(MOCK_SNAPSHOT)
  })

  it("generates files offline and reports diffs without writing when write=false", async () => {
    const result = await reviewedRefresh([mockGen()], [], {
      refresh: false,
      write: false,
    })

    expect(result.files[REL_OUT]).toBeDefined()
    expect(result.changed).toEqual([REL_OUT])
    expect(result.diffs).toHaveLength(1)
    expect(result.diffs[0]).toEqual({
      path: REL_OUT,
      before: undefined,
      after: result.files[REL_OUT],
      changed: true,
    })
    expect(existsSync(ABS_OUT)).toBe(false)
  })

  it("writes generated files when write=true", async () => {
    const result = await reviewedRefresh([mockGen()], [], {
      refresh: false,
      write: true,
    })

    expect(existsSync(ABS_OUT)).toBe(true)
    expect(readFileSync(ABS_OUT, "utf8")).toBe(result.files[REL_OUT])
  })

  it("reports no changed paths on idempotent re-run", async () => {
    await reviewedRefresh([mockGen()], [], { refresh: false, write: true })
    const second = await reviewedRefresh([mockGen()], [], {
      refresh: false,
      write: true,
    })
    expect(second.changed).toEqual([])
    expect(second.diffs[0]?.changed).toBe(false)
  })
})

describe("refreshSources", () => {
  beforeEach(() => {
    mkdirSync(TMP_DIR, { recursive: true })
  })
  afterEach(() => {
    rmSync(TMP_DIR, { recursive: true, force: true })
    if (existsSync(MOCK_SNAPSHOT)) rmSync(MOCK_SNAPSHOT)
  })

  it("fetches a refreshable source with mocked HTTP and updates the snapshot", async () => {
    const source: RefreshableSource = {
      source: { id: "mock-source", url: "https://example.com/models" },
      refreshable: true,
    }
    const payload = { data: [{ id: "mock/model", price: 1 }] }
    const results = await refreshSources([source], {
      refresh: true,
      fetchImpl: mockFetch(payload),
    })

    expect(results).toHaveLength(1)
    expect(results[0]).toMatchObject({
      id: "mock-source",
      url: "https://example.com/models",
      refreshed: true,
    })
  })

  it("skips unrefreshable sources and documents the gap", async () => {
    const results = await refreshSources([OPENAI_LLM_SOURCE], {
      refresh: true,
    })

    expect(results).toHaveLength(1)
    expect(results[0]).toMatchObject({
      id: "llm-openai",
      refreshed: false,
      skipped: true,
    })
    expect(results[0]?.notes).toContain("no stable machine-readable")
  })

  it("reports an error when env var referenced in headers is missing", async () => {
    delete process.env.MOCK_REFRESH_API_KEY
    const source: RefreshableSource = {
      source: {
        id: "auth-source",
        url: "https://example.com/models",
        headers: { Authorization: "Bearer env:MOCK_REFRESH_API_KEY" },
      },
      refreshable: true,
    }
    const results = await refreshSources([source], {
      refresh: true,
      fetchImpl: mockFetch({}),
    })

    expect(results[0]?.refreshed).toBe(false)
    expect(results[0]?.error).toContain("MOCK_REFRESH_API_KEY")
  })

  it("uses committed snapshots in offline mode and reports no refresh", async () => {
    const source: RefreshableSource = {
      source: { id: "mock-source", url: "https://example.com/models" },
      refreshable: true,
    }
    const results = await refreshSources([source], { refresh: false })

    expect(results[0]?.refreshed).toBe(false)
    expect(results[0]?.notes).toContain("Offline")
  })
})
