import { describe, it, expect, beforeEach, afterEach } from "vitest"
import { existsSync, mkdirSync, rmSync, writeFileSync, readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { runGenerators } from "../runner.js"
import { defineGenerator, type GeneratedFiles, type GeneratorContext } from "../types.js"

const HERE = dirname(fileURLToPath(import.meta.url))
// packages/catalog-sync/src/__tests__/ → packages/catalog-sync/
const PKG_DIR = join(HERE, "..", "..")
const OUT_DIR = join(PKG_DIR, ".test-tmp")
// A repo-relative path INSIDE catalog-sync (never touches model-catalog).
const REL_OUT = "packages/catalog-sync/.test-tmp/deterministic.generated.ts"
// The runner resolves REL_OUT against the monorepo root, which lands it at
// <repo>/packages/catalog-sync/.test-tmp/...  == PKG_DIR/.test-tmp/...
const ABS_OUT = join(OUT_DIR, "deterministic.generated.ts")

/** Deterministic mock generator: emits a fixed file with no sources (no network). */
function mockGen(): ReturnType<typeof defineGenerator> {
  return defineGenerator({
    name: "mock:deterministic",
    modality: "llm",
    sources: [],
    async generate(_ctx: GeneratorContext): Promise<GeneratedFiles> {
      return {
        [REL_OUT]:
          "// AUTO-GENERATED by catalog-sync mock generator (test).\n" +
          'export const MOCK = 42 as const\n',
      }
    },
  })
}

describe("runGenerators — determinism + changed-detection", () => {
  beforeEach(() => {
    mkdirSync(OUT_DIR, { recursive: true })
  })
  afterEach(() => {
    rmSync(OUT_DIR, { recursive: true, force: true })
  })

  it("produces byte-identical output across two in-memory runs (write=false)", async () => {
    const gen = mockGen()
    const a = await runGenerators([gen], { refresh: false, write: false })
    const b = await runGenerators([gen], { refresh: false, write: false })
    expect(b.files).toEqual(a.files)
    // write=false → nothing written to disk.
    expect(existsSync(ABS_OUT)).toBe(false)
    // And no changed paths reported either (file doesn't exist on disk yet,
    // but write=false short-circuits changed tracking — only content is
    // gathered). Re-assert via the write=true path below.
  })

  it("writes the file on first run (reports changed) and reports 0 changed on re-run", async () => {
    const gen = mockGen()

    // First run: file does not exist yet → written, reported as changed.
    const first = await runGenerators([gen], { refresh: false, write: true })
    expect(existsSync(ABS_OUT)).toBe(true)
    expect(first.changed).toEqual([REL_OUT])
    expect(first.files[REL_OUT]).toBeDefined()

    // Byte-identical to what landed on disk.
    expect(readFileSync(ABS_OUT, "utf8")).toBe(first.files[REL_OUT])

    // Second run: content matches disk → 0 changed, no rewrite.
    const second = await runGenerators([gen], { refresh: false, write: true })
    expect(second.changed).toEqual([])
    expect(second.files[REL_OUT]).toBe(first.files[REL_OUT])

    // Mutate disk → drift is detected on the next run.
    writeFileSync(ABS_OUT, "// tampered\n", "utf8")
    const third = await runGenerators([gen], { refresh: false, write: true })
    expect(third.changed).toEqual([REL_OUT])
  })

  it("does not mutate existing files when content is unchanged (write=true, idempotent)", async () => {
    const gen = mockGen()
    await runGenerators([gen], { refresh: false, write: true })
    const mtimeBefore = readFileSync(ABS_OUT, "utf8")
    // small delay not needed: content equality short-circuits the write.
    await runGenerators([gen], { refresh: false, write: true })
    expect(readFileSync(ABS_OUT, "utf8")).toBe(mtimeBefore)
  })
})
