/**
 * Regression: a failing live fetch during `--refresh` must reuse the committed
 * snapshot instead of crashing the whole multi-provider run. The weekly
 * Catalog Sync Action died on `fetch https://api.x.ai/v1/models failed: 403
 * Forbidden` (xAI team out of credits — a permanent failure), even though
 * snapshots/llm-xai.json was committed and every other provider refreshed
 * fine. The missing-env branch already degrades to the snapshot gracefully;
 * a non-ok response now mirrors it exactly. The throw is kept for the one
 * case where degrading is impossible: no committed snapshot to fall back to.
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest"
import { existsSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { runGenerators } from "../runner.js"
import {
  defineGenerator,
  type CatalogSource,
  type GeneratedFiles,
  type GeneratorContext,
} from "../types.js"

const HERE = dirname(fileURLToPath(import.meta.url))
// packages/catalog-sync/src/__tests__/ → packages/catalog-sync/
const PKG_DIR = join(HERE, "..", "..")

// The runner resolves snapshots against the package dir (`snapshotPath` in
// runner.ts), so these ids pin straight into snapshots/ — created/removed by
// the test itself, never touching a real committed snapshot.
const FALLBACK_SOURCE: CatalogSource = {
  id: "test-fetch-fallback",
  url: "https://api.x.ai/v1/models",
}
const ABSENT_SOURCE: CatalogSource = {
  id: "test-fetch-fallback-absent",
  url: "https://api.x.ai/v1/models",
}
const FALLBACK_SNAPSHOT_PATH = join(PKG_DIR, "snapshots", `${FALLBACK_SOURCE.id}.json`)
const SNAPSHOT_MARKER = "committed-snapshot-content"

function relOut(id: string): string {
  return `packages/catalog-sync/generated/${id}.generated.ts`
}

function fetchGenFor(src: CatalogSource): ReturnType<typeof defineGenerator> {
  return defineGenerator({
    name: `mock:${src.id}`,
    modality: "llm",
    sources: [src],
    async generate(ctx: GeneratorContext): Promise<GeneratedFiles> {
      const data = await ctx.fetchSource(src)
      return {
        [relOut(src.id)]:
          "// AUTO-GENERATED by catalog-sync fetch-fallback test.\n" +
          `export const DATA = ${JSON.stringify(data)} as const\n`,
      }
    },
  })
}

function forbiddenFetch(): typeof fetch {
  return async () =>
    ({
      ok: false,
      status: 403,
      statusText: "Forbidden",
      text: async () => '{"error":"out of credits"}',
    }) as unknown as Response
}

describe("runGenerators fetchSource — non-ok fetch falls back to committed snapshot", () => {
  const originalFetch = globalThis.fetch
  const originalStderrWrite = process.stderr.write
  let stderrChunks: string[]

  beforeEach(() => {
    globalThis.fetch = forbiddenFetch()
    stderrChunks = []
    process.stderr.write = ((chunk: unknown) => {
      stderrChunks.push(String(chunk))
      return true
    }) as typeof process.stderr.write
  })

  afterEach(() => {
    globalThis.fetch = originalFetch
    process.stderr.write = originalStderrWrite
    if (existsSync(FALLBACK_SNAPSHOT_PATH)) rmSync(FALLBACK_SNAPSHOT_PATH)
  })

  it("reuses the committed snapshot instead of throwing, and notes it on stderr", async () => {
    writeFileSync(FALLBACK_SNAPSHOT_PATH, JSON.stringify({ marker: SNAPSHOT_MARKER }), "utf8")

    const result = await runGenerators([fetchGenFor(FALLBACK_SOURCE)], {
      refresh: true,
      write: false,
    })

    // The generated file carries the committed snapshot's content…
    expect(result.files[relOut(FALLBACK_SOURCE.id)]).toContain(SNAPSHOT_MARKER)
    // …and stderr explains the graceful skip in the missing-env branch's style.
    const stderr = stderrChunks.join("")
    expect(stderr).toContain(`skipping refresh of "${FALLBACK_SOURCE.id}"`)
    expect(stderr).toContain(`fetch ${FALLBACK_SOURCE.url} failed: 403 Forbidden`)
    expect(stderr).toContain("reusing committed snapshot")
  })

  it("the fallback path emits content byte-identical to the offline (no --refresh) read", async () => {
    writeFileSync(FALLBACK_SNAPSHOT_PATH, JSON.stringify({ marker: SNAPSHOT_MARKER }), "utf8")

    const refreshed = await runGenerators([fetchGenFor(FALLBACK_SOURCE)], {
      refresh: true,
      write: false,
    })
    const offline = await runGenerators([fetchGenFor(FALLBACK_SOURCE)], {
      refresh: false,
      write: false,
    })
    expect(refreshed.files).toEqual(offline.files)
  })

  it("still throws when the fetch fails and NO committed snapshot exists", async () => {
    expect(existsSync(join(PKG_DIR, "snapshots", `${ABSENT_SOURCE.id}.json`))).toBe(false)

    await expect(
      runGenerators([fetchGenFor(ABSENT_SOURCE)], { refresh: true, write: false })
    ).rejects.toThrow(`catalog-sync: fetch ${ABSENT_SOURCE.url} failed: 403 Forbidden`)
  })
})
