/**
 * GENERATED by scripts/sync-templates.mjs from templates/workstation/versions.json.
 * DO NOT EDIT — edit versions.json and re-run the sync script instead.
 */

/** Published stable e2b template id baked with the pins below. */
export const DEFAULT_TEMPLATE = "53ybr99wdfgoebi9nee8"
export const TEMPLATE_ALIASES = {
  stable: "agentproto-workstation",
  dev: "agentproto-workstation-dev",
} as const
/**
 * What each published image was PROVEN to contain at its last real e2b
 * build. A null field means unknown (e.g. out-of-band bake) — consumers
 * must assume the image does NOT match the declared pins.
 */
export const TEMPLATES = {
  stable: {
    id: "53ybr99wdfgoebi9nee8",
    alias: "agentproto-workstation",
    baked: {
      "cli": null,
      "adapters": null,
      "builtAt": null
    },
  },
  dev: {
    id: "tnqtmeims5q9ex7j9k06",
    alias: "agentproto-workstation-dev",
    baked: {
      "cli": null,
      "adapters": null,
      "builtAt": null
    },
  },
} as const
export const BAKED_CLI_VERSION = "0.17.0"
export const BAKED_ADAPTERS = {
  "@agentproto/adapter-hermes": "0.4.10",
  "@agentproto/adapter-opencode": "1.1.10",
} as const
export const BAKED_RUNTIME = {
  "opencode-ai": "1.18.28",
} as const
export const BAKED_BASE_IMAGE = "e2bdev/code-interpreter:latest"
