export {
  defineAppConfig,
  entryMatches,
  resolveItemFiles,
  resolveItemFileInfos,
  DEFAULT_APP_FILE,
  DEFAULT_ITEMS_GLOB,
  DEFAULT_CONTRACTS_DIR,
  type AppKit,
  type AnyKit,
  type AppKitDefinition,
  type ContractDrift,
  type GateContext,
  type GateFinding,
  type GateResult,
  type GateResultFinding,
  type GateRule,
  type ItemFileInfo,
  type JsonSchemaPair,
  type JsonSchemasOptions,
  type LoadOptions,
  type MatchKey,
  type ProjectContext,
  type Resolved,
  type ResolvedItem,
  type ScopeContext,
  type ScopeFn,
  type SchemaLike,
  type VerifyFinding,
  type VerifyInput,
  type VerifyLevel,
  type VerifyReport,
} from "./define.js"
export {
  guardSource,
  memorySource,
  nodeSource,
  type ConfigSource,
  type ScopedSource,
} from "./source.js"
export {
  AppConfigError,
  canonicalJson,
  isPlainObject,
  mergeArraysByKey,
  mergeLayers,
  mergeValues,
  pick,
  normalizePrecedence,
  sha256Hex,
  sortedCopy,
  DEFAULT_PRECEDENCE,
  type Layer,
  type MergeOptions,
} from "./merge.js"
export { runCli, type CliModule } from "./cli.js"
