export {
  defineAppConfig,
  resolveItemFiles,
  DEFAULT_APP_FILE,
  DEFAULT_ITEMS_GLOB,
  DEFAULT_CONTRACTS_DIR,
  type AppKit,
  type AnyKit,
  type AppKitDefinition,
  type ContractDrift,
  type GateFinding,
  type GateResult,
  type GateResultFinding,
  type GateRule,
  type JsonSchemaPair,
  type LoadOptions,
  type Resolved,
  type ResolvedItem,
  type ScopeFn,
  type VerifyFinding,
  type VerifyInput,
  type VerifyLevel,
  type VerifyReport,
} from "./define.js"
export {
  AppConfigError,
  canonicalJson,
  isPlainObject,
  mergeLayers,
  mergeValues,
  pick,
  normalizePrecedence,
  sha256Hex,
  sortedCopy,
  DEFAULT_PRECEDENCE,
  type Layer,
} from "./merge.js"
export { runCli, type CliModule } from "./cli.js"
