#!/usr/bin/env node
/**
 * Build the Claude Code hook files in `files/.claude/hooks/` from
 * templates by stamping in the canonical mention-parser source from
 * `@agentproto/agent-runtime/util/mention-parser`.
 *
 * Why this exists: the hook runs from `.claude/` in the user's repo,
 * which has no module resolution at hook-execution time. So the parser
 * has to be physically inlined into the hook file. Stamping at build
 * time is the only way to keep one canonical source and one shipped
 * artifact in sync.
 *
 * Outputs are gitignored — they're build artifacts, not source.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { createRequire } from "node:module"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(here, "..")
const require = createRequire(import.meta.url)

const MARKER = "// %% MENTION_PARSER %%"

const targets = [
  {
    template: "templates/user-prompt-submit.template.mjs",
    output: "files/.claude/hooks/user-prompt-submit.mjs",
  },
]

const parserPath = require.resolve(
  "@agentproto/agent-runtime/util/mention-parser"
)
const parserSource = await readFile(parserPath, "utf8")

for (const { template, output } of targets) {
  const templateAbs = resolve(pkgRoot, template)
  const outputAbs = resolve(pkgRoot, output)
  const raw = await readFile(templateAbs, "utf8")
  if (!raw.includes(MARKER)) {
    process.stderr.write(
      `build-hooks: template ${template} is missing the marker '${MARKER}'.\n`
    )
    process.exit(1)
  }
  const inlined = withInlineBanner(parserSource)
  const stamped = raw.replace(MARKER, inlined)
  await mkdir(dirname(outputAbs), { recursive: true })
  await writeFile(outputAbs, stamped, "utf8")
  process.stderr.write(`build-hooks: ${template} → ${output}\n`)
}

function withInlineBanner(source) {
  const stripped = source
    // Drop the JSDoc-style banner at the top — the template already
    // explains why the parser is inlined.
    .replace(/^\s*\/\*\*[\s\S]*?\*\/\s*/, "")
    // Drop the leading `export` keywords; the inlined function lives
    // in the hook's module scope.
    .replace(/^export\s+function/gm, "function")
    .trim()
  return [
    "// ── BEGIN inlined from @agentproto/agent-runtime/util/mention-parser ──",
    "// ── DO NOT EDIT — regenerated by scripts/build-hooks.mjs ──",
    stripped,
    "// ── END inlined ──",
  ].join("\n")
}
