import { z } from "zod"
import {
  envelope,
  isoDatetimeOrDateSchema,
  kebabSlugSchema,
  partyRefStrictSchema,
} from "./_common.js"

/**
 * agentagencies/v1 — `CAPACITY.md` doctype.
 *
 * Operator availability, current load, vertical specialization. Per-agent or
 * per-team. Used by routing logic to pick who gets a new engagement / step.
 */

const availabilityWindowSchema = z.object({
  /** ISO weekday name or 0-6 (Mon=0..Sun=6). */
  weekday: z.union([
    z.number().min(0).max(6),
    z.enum(["mon", "tue", "wed", "thu", "fri", "sat", "sun"]),
  ]),
  /** "HH:MM" 24h start time (in operator's timezone). */
  start: z.string().regex(/^\d{2}:\d{2}$/),
  end: z.string().regex(/^\d{2}:\d{2}$/),
})

export const capacityFrontmatterSchema = z.object({
  ...envelope("capacity"),

  /** The party this capacity describes (operator, agent, or team). */
  for: partyRefStrictSchema,

  /** Recurring availability windows (in operator's timezone). */
  availability: z.array(availabilityWindowSchema).default([]),

  /** Maximum concurrent engagements. */
  maxConcurrentEngagements: z.number().positive().optional(),

  /** Maximum hours per week of billable work. */
  maxBillableHoursPerWeek: z.number().positive().optional(),

  /** Vertical specializations (slugs of services or templates). */
  specializations: z.array(kebabSlugSchema).default([]),

  /** Current load — denorm of in-flight work (regenerated by runtime). */
  currentEngagementCount: z.number().nonnegative().optional(),
  currentBillableHoursThisWeek: z.number().nonnegative().optional(),

  /** Out-of-office / unavailability windows. */
  blockedWindows: z
    .array(
      z.object({
        from: isoDatetimeOrDateSchema,
        until: isoDatetimeOrDateSchema,
        reason: z.string().optional(),
      })
    )
    .default([]),
})
export type CapacityFrontmatter = z.infer<typeof capacityFrontmatterSchema>

export interface Capacity {
  frontmatter: CapacityFrontmatter
  body: string
}

export const CAPACITY_FILENAME = "CAPACITY.md" as const
