// AUTO-GENERATED by @agentproto/catalog-sync (llm:context-windows).
// Do not edit by hand — re-run `pnpm --filter @agentproto/catalog-sync generate --refresh`.
// Sources: api.anthropic.com/v1/models, api.groq.com/openai/v1/models,
//         api.x.ai/v1/models, api.moonshot.ai/v1/models
// Context window (max input tokens) + max output tokens per live model id.
// NOT pricing — see LLM_PRICING_CATALOG / OPENROUTER_ROUTES in catalog.ts.

export interface ContextWindowEntry {
  contextWindow: number
  maxOutput?: number
  displayName?: string
  provider: "anthropic" | "groq" | "xai" | "moonshot"
}

export const CONTEXT_WINDOWS: Record<string, ContextWindowEntry> = {
  "allam-2-7b": { contextWindow: 4096, maxOutput: 4096, provider: "groq" },
  "canopylabs/orpheus-arabic-saudi": { contextWindow: 4000, maxOutput: 50000, provider: "groq" },
  "canopylabs/orpheus-v1-english": { contextWindow: 4000, maxOutput: 50000, provider: "groq" },
  "claude-fable-5": { contextWindow: 1000000, maxOutput: 128000, displayName: "Claude Fable 5", provider: "anthropic" },
  "claude-haiku-4-5-20251001": { contextWindow: 200000, maxOutput: 64000, displayName: "Claude Haiku 4.5", provider: "anthropic" },
  "claude-opus-4-5-20251101": { contextWindow: 200000, maxOutput: 64000, displayName: "Claude Opus 4.5", provider: "anthropic" },
  "claude-opus-4-6": { contextWindow: 1000000, maxOutput: 128000, displayName: "Claude Opus 4.6", provider: "anthropic" },
  "claude-opus-4-7": { contextWindow: 1000000, maxOutput: 128000, displayName: "Claude Opus 4.7", provider: "anthropic" },
  "claude-opus-4-8": { contextWindow: 1000000, maxOutput: 128000, displayName: "Claude Opus 4.8", provider: "anthropic" },
  "claude-opus-5": { contextWindow: 1000000, maxOutput: 128000, displayName: "Claude Opus 5", provider: "anthropic" },
  "claude-sonnet-4-5-20250929": { contextWindow: 1000000, maxOutput: 64000, displayName: "Claude Sonnet 4.5", provider: "anthropic" },
  "claude-sonnet-4-6": { contextWindow: 1000000, maxOutput: 128000, displayName: "Claude Sonnet 4.6", provider: "anthropic" },
  "claude-sonnet-5": { contextWindow: 1000000, maxOutput: 128000, displayName: "Claude Sonnet 5", provider: "anthropic" },
  "grok-4.20-0309-non-reasoning": { contextWindow: 1000000, provider: "xai" },
  "grok-4.20-0309-reasoning": { contextWindow: 1000000, provider: "xai" },
  "grok-4.20-multi-agent-0309": { contextWindow: 1000000, provider: "xai" },
  "grok-4.3": { contextWindow: 1000000, provider: "xai" },
  "grok-4.5": { contextWindow: 500000, provider: "xai" },
  "grok-4.6": { contextWindow: 500000, provider: "xai" },
  "grok-build-0.1": { contextWindow: 256000, provider: "xai" },
  "grok-imagine-image": { contextWindow: 8000, provider: "xai" },
  "grok-imagine-image-2.0": { contextWindow: 8000, provider: "xai" },
  "grok-imagine-image-quality": { contextWindow: 8000, provider: "xai" },
  "groq/compound": { contextWindow: 131072, maxOutput: 8192, provider: "groq" },
  "groq/compound-mini": { contextWindow: 131072, maxOutput: 8192, provider: "groq" },
  "kimi-k2.5": { contextWindow: 262144, provider: "moonshot" },
  "kimi-k2.6": { contextWindow: 262144, provider: "moonshot" },
  "kimi-k2.7-code": { contextWindow: 262144, provider: "moonshot" },
  "kimi-k2.7-code-highspeed": { contextWindow: 262144, provider: "moonshot" },
  "kimi-k3": { contextWindow: 1048576, provider: "moonshot" },
  "llama-3.1-8b-instant": { contextWindow: 131072, maxOutput: 131072, provider: "groq" },
  "llama-3.3-70b-versatile": { contextWindow: 131072, maxOutput: 32768, provider: "groq" },
  "meta-llama/llama-4-scout-17b-16e-instruct": { contextWindow: 131072, maxOutput: 8192, provider: "groq" },
  "meta-llama/llama-prompt-guard-2-22m": { contextWindow: 512, maxOutput: 512, provider: "groq" },
  "meta-llama/llama-prompt-guard-2-86m": { contextWindow: 512, maxOutput: 512, provider: "groq" },
  "moonshot-v1-128k": { contextWindow: 131072, provider: "moonshot" },
  "moonshot-v1-128k-vision-preview": { contextWindow: 131072, provider: "moonshot" },
  "moonshot-v1-32k": { contextWindow: 32768, provider: "moonshot" },
  "moonshot-v1-32k-vision-preview": { contextWindow: 32768, provider: "moonshot" },
  "moonshot-v1-8k": { contextWindow: 8192, provider: "moonshot" },
  "moonshot-v1-8k-vision-preview": { contextWindow: 8192, provider: "moonshot" },
  "moonshot-v1-auto": { contextWindow: 131072, provider: "moonshot" },
  "openai/gpt-oss-120b": { contextWindow: 131072, maxOutput: 65536, provider: "groq" },
  "openai/gpt-oss-20b": { contextWindow: 131072, maxOutput: 65536, provider: "groq" },
  "openai/gpt-oss-safeguard-20b": { contextWindow: 131072, maxOutput: 65536, provider: "groq" },
  "qwen/qwen3-32b": { contextWindow: 131072, maxOutput: 40960, provider: "groq" },
  "qwen/qwen3.6-27b": { contextWindow: 131072, maxOutput: 32768, provider: "groq" },
  "whisper-large-v3": { contextWindow: 448, maxOutput: 448, provider: "groq" },
  "whisper-large-v3-turbo": { contextWindow: 448, maxOutput: 448, provider: "groq" },
}
