// AUTO-GENERATED by @agentproto/catalog-sync (llm:huggingface).
// Do not edit by hand — re-run `pnpm --filter @agentproto/catalog-sync generate`.
// Source: https://router.huggingface.co/v1/models
// Per-model LIVE inference providers from the HuggingFace router. HF wire
// ids are case-sensitive and preserved verbatim. Provider entries are
// SPARSE on some models — every field below except provider/status is
// optional and emitted only when the upstream response carries it. Only
// providers with status === "live" are kept; models with zero live
// providers are skipped. inputPer1M/outputPer1M are USD per 1M tokens
// (HuggingFace router convention — already at that scale, unlike
// OpenRouter's per-token strings).

export interface HuggingFaceRouteProvider {
  provider: string
  status: string
  contextLength?: number
  inputPer1M?: number
  outputPer1M?: number
  supportsTools?: boolean
  supportsStructuredOutput?: boolean
}

export interface HuggingFaceRoute {
  wireId: string
  providers: HuggingFaceRouteProvider[]
}

export const HUGGINGFACE_ROUTES: Record<string, HuggingFaceRoute> = {
  "CohereLabs/aya-expanse-32b": {
    wireId: "CohereLabs/aya-expanse-32b",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "CohereLabs/aya-vision-32b": {
    wireId: "CohereLabs/aya-vision-32b",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "CohereLabs/c4ai-command-a-03-2025": {
    wireId: "CohereLabs/c4ai-command-a-03-2025",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "CohereLabs/c4ai-command-r-08-2024": {
    wireId: "CohereLabs/c4ai-command-r-08-2024",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "CohereLabs/c4ai-command-r7b-12-2024": {
    wireId: "CohereLabs/c4ai-command-r7b-12-2024",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "CohereLabs/c4ai-command-r7b-arabic-02-2025": {
    wireId: "CohereLabs/c4ai-command-r7b-arabic-02-2025",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "CohereLabs/command-a-reasoning-08-2025": {
    wireId: "CohereLabs/command-a-reasoning-08-2025",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "CohereLabs/command-a-translate-08-2025": {
    wireId: "CohereLabs/command-a-translate-08-2025",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "CohereLabs/command-a-vision-07-2025": {
    wireId: "CohereLabs/command-a-vision-07-2025",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "CohereLabs/tiny-aya-earth": {
    wireId: "CohereLabs/tiny-aya-earth",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "CohereLabs/tiny-aya-fire": {
    wireId: "CohereLabs/tiny-aya-fire",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "CohereLabs/tiny-aya-global": {
    wireId: "CohereLabs/tiny-aya-global",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "CohereLabs/tiny-aya-water": {
    wireId: "CohereLabs/tiny-aya-water",
    providers: [
      {
        provider: "cohere",
        status: "live",
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "MiniMaxAI/MiniMax-M1-80k": {
    wireId: "MiniMaxAI/MiniMax-M1-80k",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 1000000,
        inputPer1M: 0.55,
        outputPer1M: 2.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "MiniMaxAI/MiniMax-M2": {
    wireId: "MiniMaxAI/MiniMax-M2",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 204800,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "MiniMaxAI/MiniMax-M2.1": {
    wireId: "MiniMaxAI/MiniMax-M2.1",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 204800,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "MiniMaxAI/MiniMax-M2.5": {
    wireId: "MiniMaxAI/MiniMax-M2.5",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 204800,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "MiniMaxAI/MiniMax-M2.7": {
    wireId: "MiniMaxAI/MiniMax-M2.7",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 196608,
        inputPer1M: 0.25,
        outputPer1M: 1,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 196608,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 204800,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "MiniMaxAI/MiniMax-M3": {
    wireId: "MiniMaxAI/MiniMax-M3",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 524288,
        inputPer1M: 0.28,
        outputPer1M: 1.1,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 512000,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 1000000,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 524288,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "NousResearch/Hermes-3-Llama-3.1-70B": {
    wireId: "NousResearch/Hermes-3-Llama-3.1-70B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.7,
        outputPer1M: 0.7,
        supportsTools: false,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      }
    ],
  },
  "Qwen/Qwen2.5-72B-Instruct": {
    wireId: "Qwen/Qwen2.5-72B-Instruct",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 32768,
        inputPer1M: 0.36,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 32000,
        inputPer1M: 0.38,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen2.5-Coder-32B-Instruct": {
    wireId: "Qwen/Qwen2.5-Coder-32B-Instruct",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.06,
        outputPer1M: 0.2,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen2.5-Coder-3B-Instruct": {
    wireId: "Qwen/Qwen2.5-Coder-3B-Instruct",
    providers: [
      {
        provider: "nscale",
        status: "live",
        contextLength: 32768,
        inputPer1M: 0.01,
        outputPer1M: 0.03,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen2.5-Coder-7B-Instruct": {
    wireId: "Qwen/Qwen2.5-Coder-7B-Instruct",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.01,
        outputPer1M: 0.03,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen2.5-VL-72B-Instruct": {
    wireId: "Qwen/Qwen2.5-VL-72B-Instruct",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "ovhcloud",
        status: "live",
        contextLength: 32768,
        inputPer1M: 1.01,
        outputPer1M: 1.01,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3-14B": {
    wireId: "Qwen/Qwen3-14B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 40960,
        inputPer1M: 0.12,
        outputPer1M: 0.24,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 40960,
        inputPer1M: 0.07,
        outputPer1M: 0.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3-235B-A22B": {
    wireId: "Qwen/Qwen3-235B-A22B",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 40960,
        inputPer1M: 0.2,
        outputPer1M: 0.8,
        supportsTools: false,
        supportsStructuredOutput: false,
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 32000,
        inputPer1M: 0.2,
        outputPer1M: 0.6,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3-235B-A22B-Instruct-2507": {
    wireId: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.09,
        outputPer1M: 0.55,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.09,
        outputPer1M: 0.58,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 32768,
        inputPer1M: 0.2,
        outputPer1M: 0.6,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "scaleway",
        status: "live",
        inputPer1M: 0.855,
        outputPer1M: 2.565,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3-235B-A22B-Thinking-2507": {
    wireId: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.23,
        outputPer1M: 2.3,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.3,
        outputPer1M: 3,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3-30B-A3B": {
    wireId: "Qwen/Qwen3-30B-A3B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 40960,
        inputPer1M: 0.12,
        outputPer1M: 0.5,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3-32B": {
    wireId: "Qwen/Qwen3-32B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 40960,
        inputPer1M: 0.08,
        outputPer1M: 0.28,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 40960,
        inputPer1M: 0.08,
        outputPer1M: 0.25,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3-4B-Instruct-2507": {
    wireId: "Qwen/Qwen3-4B-Instruct-2507",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.01,
        outputPer1M: 0.03,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3-4B-Thinking-2507": {
    wireId: "Qwen/Qwen3-4B-Thinking-2507",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.01,
        outputPer1M: 0.03,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3-8B": {
    wireId: "Qwen/Qwen3-8B",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 40960,
        inputPer1M: 0.07,
        outputPer1M: 0.18,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3-Coder-30B-A3B-Instruct": {
    wireId: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "scaleway",
        status: "live",
        inputPer1M: 0.228,
        outputPer1M: 0.912,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3-Coder-480B-A35B-Instruct": {
    wireId: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.38,
        outputPer1M: 1.55,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3-Coder-Next": {
    wireId: "Qwen/Qwen3-Coder-Next",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.2,
        outputPer1M: 1.5,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3-Next-80B-A3B-Instruct": {
    wireId: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.09,
        outputPer1M: 1.1,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.15,
        outputPer1M: 1.5,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3-VL-235B-A22B-Instruct": {
    wireId: "Qwen/Qwen3-VL-235B-A22B-Instruct",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.2,
        outputPer1M: 0.88,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.3,
        outputPer1M: 1.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3-VL-235B-A22B-Thinking": {
    wireId: "Qwen/Qwen3-VL-235B-A22B-Thinking",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.98,
        outputPer1M: 3.95,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3-VL-30B-A3B-Instruct": {
    wireId: "Qwen/Qwen3-VL-30B-A3B-Instruct",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.15,
        outputPer1M: 0.6,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.2,
        outputPer1M: 0.7,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3.5-122B-A10B": {
    wireId: "Qwen/Qwen3.5-122B-A10B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.29,
        outputPer1M: 2.4,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.4,
        outputPer1M: 3.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3.5-27B": {
    wireId: "Qwen/Qwen3.5-27B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.26,
        outputPer1M: 2.6,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.3,
        outputPer1M: 2.4,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3.5-35B-A3B": {
    wireId: "Qwen/Qwen3.5-35B-A3B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.14,
        outputPer1M: 1,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.25,
        outputPer1M: 2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Qwen/Qwen3.5-397B-A17B": {
    wireId: "Qwen/Qwen3.5-397B-A17B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.45,
        outputPer1M: 3,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.6,
        outputPer1M: 3.6,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "ovhcloud",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.71,
        outputPer1M: 4.25,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "scaleway",
        status: "live",
        inputPer1M: 0.684,
        outputPer1M: 4.104,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3.5-9B": {
    wireId: "Qwen/Qwen3.5-9B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.1,
        outputPer1M: 0.15,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "ovhcloud",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.12,
        outputPer1M: 0.18,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.17,
        outputPer1M: 0.25,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3.6-27B": {
    wireId: "Qwen/Qwen3.6-27B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.32,
        outputPer1M: 3.2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "ovhcloud",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.47,
        outputPer1M: 3.19,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3.6-35B-A3B": {
    wireId: "Qwen/Qwen3.6-35B-A3B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.1,
        outputPer1M: 0.95,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "scaleway",
        status: "live",
        inputPer1M: 0.285,
        outputPer1M: 1.71,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "Qwen/Qwen3.8-2.4T-A95B": {
    wireId: "Qwen/Qwen3.8-2.4T-A95B",
    providers: [
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 262144,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 1010000,
        inputPer1M: 2.5,
        outputPer1M: 6.25,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Sao10K/L3-8B-Lunaris-v1": {
    wireId: "Sao10K/L3-8B-Lunaris-v1",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 8192,
        inputPer1M: 0.05,
        outputPer1M: 0.05,
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "Sao10K/L3-8B-Stheno-v3.2": {
    wireId: "Sao10K/L3-8B-Stheno-v3.2",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 8192,
        inputPer1M: 0.05,
        outputPer1M: 0.05,
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "XiaomiMiMo/MiMo-V2.5": {
    wireId: "XiaomiMiMo/MiMo-V2.5",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.4,
        outputPer1M: 2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      }
    ],
  },
  "XiaomiMiMo/MiMo-V2.5-Pro": {
    wireId: "XiaomiMiMo/MiMo-V2.5-Pro",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1,
        outputPer1M: 3,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "aisingapore/Gemma-SEA-LION-v4-27B-IT": {
    wireId: "aisingapore/Gemma-SEA-LION-v4-27B-IT",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "publicai",
        status: "live",
        inputPer1M: 0.2,
        outputPer1M: 0.4,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "aisingapore/Qwen-SEA-LION-v4-32B-IT": {
    wireId: "aisingapore/Qwen-SEA-LION-v4-32B-IT",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "publicai",
        status: "live",
        inputPer1M: 0.25,
        outputPer1M: 0.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "alpindale/WizardLM-2-8x22B": {
    wireId: "alpindale/WizardLM-2-8x22B",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 65535,
        inputPer1M: 0.62,
        outputPer1M: 0.62,
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT": {
    wireId: "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 123000,
        inputPer1M: 0.42,
        outputPer1M: 1.25,
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "deepseek-ai/DeepSeek-R1": {
    wireId: "deepseek-ai/DeepSeek-R1",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 64000,
        inputPer1M: 0.7,
        outputPer1M: 2.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-R1-0528": {
    wireId: "deepseek-ai/DeepSeek-R1-0528",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.5,
        outputPer1M: 2.15,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.7,
        outputPer1M: 2.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-R1-Distill-Llama-70B": {
    wireId: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 8192,
        inputPer1M: 0.8,
        outputPer1M: 0.8,
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "deepseek-ai/DeepSeek-R1-Distill-Llama-8B": {
    wireId: "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.05,
        outputPer1M: 0.05,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B": {
    wireId: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.2,
        outputPer1M: 0.2,
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B": {
    wireId: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
    providers: [
      {
        provider: "nscale",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.15,
        outputPer1M: 0.15,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V3": {
    wireId: "deepseek-ai/DeepSeek-V3",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.32,
        outputPer1M: 0.89,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 64000,
        inputPer1M: 0.4,
        outputPer1M: 1.3,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V3-0324": {
    wireId: "deepseek-ai/DeepSeek-V3-0324",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.24,
        outputPer1M: 0.9,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.27,
        outputPer1M: 1.12,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V3.1": {
    wireId: "deepseek-ai/DeepSeek-V3.1",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.25,
        outputPer1M: 0.95,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.27,
        outputPer1M: 1,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V3.1-Terminus": {
    wireId: "deepseek-ai/DeepSeek-V3.1-Terminus",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.27,
        outputPer1M: 0.95,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.27,
        outputPer1M: 1,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V3.2": {
    wireId: "deepseek-ai/DeepSeek-V3.2",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.26,
        outputPer1M: 0.38,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.269,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V3.2-Exp": {
    wireId: "deepseek-ai/DeepSeek-V3.2-Exp",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.27,
        outputPer1M: 0.41,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V4-Flash": {
    wireId: "deepseek-ai/DeepSeek-V4-Flash",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.09,
        outputPer1M: 0.18,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.14,
        outputPer1M: 0.28,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V4-Flash-0731": {
    wireId: "deepseek-ai/DeepSeek-V4-Flash-0731",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.13,
        outputPer1M: 0.26,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.08,
        outputPer1M: 0.18,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 1048576,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.44,
        outputPer1M: 1.32,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.14,
        outputPer1M: 0.28,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V4-Pro": {
    wireId: "deepseek-ai/DeepSeek-V4-Pro",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.74,
        outputPer1M: 3.48,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.3,
        outputPer1M: 2.6,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.74,
        outputPer1M: 3.48,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.6,
        outputPer1M: 3.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 512000,
        inputPer1M: 1.74,
        outputPer1M: 3.48,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "deepseek-ai/DeepSeek-V4-Pro-0813": {
    wireId: "deepseek-ai/DeepSeek-V4-Pro-0813",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.32,
        outputPer1M: 3.96,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 1048576,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.32,
        outputPer1M: 3.96,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.32,
        outputPer1M: 3.96,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "google/gemma-3-12b-it": {
    wireId: "google/gemma-3-12b-it",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.05,
        outputPer1M: 0.15,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      }
    ],
  },
  "google/gemma-3-27b-it": {
    wireId: "google/gemma-3-27b-it",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.08,
        outputPer1M: 0.16,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      }
    ],
  },
  "google/gemma-3-4b-it": {
    wireId: "google/gemma-3-4b-it",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.05,
        outputPer1M: 0.1,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      }
    ],
  },
  "google/gemma-3n-E4B-it": {
    wireId: "google/gemma-3n-E4B-it",
    providers: [
      {
        provider: "together",
        status: "live",
        contextLength: 32768,
        inputPer1M: 0.06,
        outputPer1M: 0.12,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "google/gemma-4-26B-A4B-it": {
    wireId: "google/gemma-4-26B-A4B-it",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.07,
        outputPer1M: 0.34,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.13,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "scaleway",
        status: "live",
        inputPer1M: 0.285,
        outputPer1M: 0.57,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "google/gemma-4-31B-it": {
    wireId: "google/gemma-4-31B-it",
    providers: [
      {
        provider: "cerebras",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.99,
        outputPer1M: 1.49,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.13,
        outputPer1M: 0.38,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.14,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.39,
        outputPer1M: 0.97,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "inclusionAI/Ling-2.6-1T": {
    wireId: "inclusionAI/Ling-2.6-1T",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.3,
        outputPer1M: 2.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "inclusionAI/Ling-3.0-flash": {
    wireId: "inclusionAI/Ling-3.0-flash",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.06,
        outputPer1M: 0.18,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "meta-llama/Llama-3.1-8B-Instruct": {
    wireId: "meta-llama/Llama-3.1-8B-Instruct",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.02,
        outputPer1M: 0.05,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 16384,
        inputPer1M: 0.02,
        outputPer1M: 0.05,
        supportsTools: false,
        supportsStructuredOutput: false,
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.06,
        outputPer1M: 0.06,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "meta-llama/Llama-3.3-70B-Instruct": {
    wireId: "meta-llama/Llama-3.3-70B-Instruct",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 12288,
        inputPer1M: 0.135,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "ovhcloud",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.74,
        outputPer1M: 0.74,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "scaleway",
        status: "live",
        inputPer1M: 1.026,
        outputPer1M: 1.026,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 131072,
        inputPer1M: 1.04,
        outputPer1M: 1.04,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8": {
    wireId: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.27,
        outputPer1M: 0.85,
        supportsTools: false,
        supportsStructuredOutput: true,
      }
    ],
  },
  "meta-llama/Llama-4-Scout-17B-16E-Instruct": {
    wireId: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 327680,
        inputPer1M: 0.1,
        outputPer1M: 0.3,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.18,
        outputPer1M: 0.59,
        supportsTools: false,
        supportsStructuredOutput: false,
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 890000,
        inputPer1M: 0.09,
        outputPer1M: 0.29,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "meta-llama/Llama-Guard-4-12B": {
    wireId: "meta-llama/Llama-Guard-4-12B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 163840,
        inputPer1M: 0.18,
        outputPer1M: 0.18,
        supportsTools: false,
        supportsStructuredOutput: false,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.2,
        outputPer1M: 0.2,
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "meta-models/Muse-Glimmer-30B": {
    wireId: "meta-models/Muse-Glimmer-30B",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.3,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 131072,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.35,
        outputPer1M: 1.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "microsoft/phi-4": {
    wireId: "microsoft/phi-4",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 16384,
        inputPer1M: 0.07,
        outputPer1M: 0.14,
        supportsTools: false,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      }
    ],
  },
  "moonshotai/Kimi-K2-Instruct": {
    wireId: "moonshotai/Kimi-K2-Instruct",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.57,
        outputPer1M: 2.3,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "moonshotai/Kimi-K2-Instruct-0905": {
    wireId: "moonshotai/Kimi-K2-Instruct-0905",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.6,
        outputPer1M: 2.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "moonshotai/Kimi-K2.5": {
    wireId: "moonshotai/Kimi-K2.5",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.45,
        outputPer1M: 2.25,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.6,
        outputPer1M: 3,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "moonshotai/Kimi-K2.6": {
    wireId: "moonshotai/Kimi-K2.6",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 262000,
        inputPer1M: 0.95,
        outputPer1M: 4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.75,
        outputPer1M: 3.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.95,
        outputPer1M: 4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.8,
        outputPer1M: 3.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "moonshotai/Kimi-K2.7-Code": {
    wireId: "moonshotai/Kimi-K2.7-Code",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 262000,
        inputPer1M: 0.95,
        outputPer1M: 4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.68,
        outputPer1M: 3.4,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.95,
        outputPer1M: 4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.95,
        outputPer1M: 4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.95,
        outputPer1M: 4,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "moonshotai/Kimi-K3": {
    wireId: "moonshotai/Kimi-K3",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 3,
        outputPer1M: 15,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 2.85,
        outputPer1M: 14.25,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 3,
        outputPer1M: 15,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 3,
        outputPer1M: 15,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16": {
    wireId: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 1,
        outputPer1M: 5,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4": {
    wireId: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4",
    providers: [
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.6,
        outputPer1M: 2.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 512288,
        inputPer1M: 0.6,
        outputPer1M: 3.6,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16": {
    wireId: "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
    providers: [
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 262144,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "openai/gpt-oss-120b": {
    wireId: "openai/gpt-oss-120b",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 128072,
        inputPer1M: 0.1,
        outputPer1M: 0.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "cerebras",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.35,
        outputPer1M: 0.75,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.037,
        outputPer1M: 0.17,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.15,
        outputPer1M: 0.6,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "groq",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.15,
        outputPer1M: 0.75,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.05,
        outputPer1M: 0.25,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.1,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "ovhcloud",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.09,
        outputPer1M: 0.47,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "scaleway",
        status: "live",
        inputPer1M: 0.171,
        outputPer1M: 0.684,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.15,
        outputPer1M: 0.6,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "openai/gpt-oss-20b": {
    wireId: "openai/gpt-oss-20b",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.03,
        outputPer1M: 0.14,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.07,
        outputPer1M: 0.3,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "groq",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.1,
        outputPer1M: 0.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.04,
        outputPer1M: 0.15,
        supportsTools: false,
        supportsStructuredOutput: true,
      },
      {
        provider: "nscale",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.05,
        outputPer1M: 0.2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "ovhcloud",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.05,
        outputPer1M: 0.18,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.05,
        outputPer1M: 0.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "openai/gpt-oss-safeguard-20b": {
    wireId: "openai/gpt-oss-safeguard-20b",
    providers: [
      {
        provider: "groq",
        status: "live",
        contextLength: 131072,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "pearl-ai/Gemma-4-31B-it-pearl": {
    wireId: "pearl-ai/Gemma-4-31B-it-pearl",
    providers: [
      {
        provider: "together",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.28,
        outputPer1M: 0.86,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "prism-ml/Ternary-Bonsai-27B-AWQ-4bit": {
    wireId: "prism-ml/Ternary-Bonsai-27B-AWQ-4bit",
    providers: [
      {
        provider: "together",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0,
        outputPer1M: 0,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "prism-ml/Ternary-Bonsai-27B-gguf": {
    wireId: "prism-ml/Ternary-Bonsai-27B-gguf",
    providers: [
      {
        provider: "together",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0,
        outputPer1M: 0,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "speakleash/Bielik-11B-v3.0-Instruct": {
    wireId: "speakleash/Bielik-11B-v3.0-Instruct",
    providers: [
      {
        provider: "publicai",
        status: "live",
        inputPer1M: 0.4,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "stepfun-ai/Step-3.5-Flash": {
    wireId: "stepfun-ai/Step-3.5-Flash",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.1,
        outputPer1M: 0.3,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      }
    ],
  },
  "stepfun-ai/Step-3.7-Flash": {
    wireId: "stepfun-ai/Step-3.7-Flash",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.2,
        outputPer1M: 1.15,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      }
    ],
  },
  "swiss-ai/Apertus-70B-Instruct-2509": {
    wireId: "swiss-ai/Apertus-70B-Instruct-2509",
    providers: [
      {
        provider: "publicai",
        status: "live",
        inputPer1M: 0.82,
        outputPer1M: 2.92,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "swiss-ai/Apertus-8B-Instruct-2509": {
    wireId: "swiss-ai/Apertus-8B-Instruct-2509",
    providers: [
      {
        provider: "publicai",
        status: "live",
        inputPer1M: 0.82,
        outputPer1M: 2.92,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "swiss-ai/Apertus-v1.5-70B": {
    wireId: "swiss-ai/Apertus-v1.5-70B",
    providers: [
      {
        provider: "publicai",
        status: "live",
        inputPer1M: 0.82,
        outputPer1M: 2.92,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "tencent/Hy3": {
    wireId: "tencent/Hy3",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 262144,
        inputPer1M: 0.14,
        outputPer1M: 0.58,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "thinkingmachines/Inkling": {
    wireId: "thinkingmachines/Inkling",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1,
        outputPer1M: 4.05,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 524288,
        inputPer1M: 0.95,
        outputPer1M: 4.05,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 1048576,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 524288,
        inputPer1M: 1,
        outputPer1M: 4.05,
        supportsTools: true,
        supportsStructuredOutput: true,
      }
    ],
  },
  "thinkingmachines/Inkling-Small": {
    wireId: "thinkingmachines/Inkling-Small",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.5,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 524288,
        inputPer1M: 0.45,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 524288,
        inputPer1M: 0.5,
        outputPer1M: 1.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/AutoGLM-Phone-9B-Multilingual": {
    wireId: "zai-org/AutoGLM-Phone-9B-Multilingual",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 65536,
        inputPer1M: 0.035,
        outputPer1M: 0.138,
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4-32B-0414": {
    wireId: "zai-org/GLM-4-32B-0414",
    providers: [
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 32000,
        inputPer1M: 0.55,
        outputPer1M: 1.66,
        supportsTools: false,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.5": {
    wireId: "zai-org/GLM-4.5",
    providers: [
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.5-Air": {
    wireId: "zai-org/GLM-4.5-Air",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.13,
        outputPer1M: 0.85,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.5V": {
    wireId: "zai-org/GLM-4.5V",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 65536,
        inputPer1M: 0.6,
        outputPer1M: 1.8,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.5V-FP8": {
    wireId: "zai-org/GLM-4.5V-FP8",
    providers: [
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.6": {
    wireId: "zai-org/GLM-4.6",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 202752,
        inputPer1M: 0.5,
        outputPer1M: 2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 204800,
        inputPer1M: 0.55,
        outputPer1M: 2.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.6-FP8": {
    wireId: "zai-org/GLM-4.6-FP8",
    providers: [
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.6V": {
    wireId: "zai-org/GLM-4.6V",
    providers: [
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.6V-FP8": {
    wireId: "zai-org/GLM-4.6V-FP8",
    providers: [
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.6V-Flash": {
    wireId: "zai-org/GLM-4.6V-Flash",
    providers: [
      {
        provider: "novita",
        status: "live",
        contextLength: 131072,
        inputPer1M: 0.3,
        outputPer1M: 0.9,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.7": {
    wireId: "zai-org/GLM-4.7",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 200000,
        inputPer1M: 0.6,
        outputPer1M: 2.2,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 202752,
        inputPer1M: 0.4,
        outputPer1M: 1.75,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 204800,
        inputPer1M: 0.6,
        outputPer1M: 2.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.7-FP8": {
    wireId: "zai-org/GLM-4.7-FP8",
    providers: [
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-4.7-Flash": {
    wireId: "zai-org/GLM-4.7-Flash",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 202752,
        inputPer1M: 0.06,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 200000,
        inputPer1M: 0.07,
        outputPer1M: 0.4,
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-5": {
    wireId: "zai-org/GLM-5",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 202752,
        inputPer1M: 0.6,
        outputPer1M: 2.08,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 202800,
        inputPer1M: 1,
        outputPer1M: 3.2,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-5.1": {
    wireId: "zai-org/GLM-5.1",
    providers: [
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 202752,
        inputPer1M: 1.05,
        outputPer1M: 3.5,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-5.1-FP8": {
    wireId: "zai-org/GLM-5.1-FP8",
    providers: [
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-5.2": {
    wireId: "zai-org/GLM-5.2",
    providers: [
      {
        provider: "baseten",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.4,
        outputPer1M: 4.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "deepinfra",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 0.75,
        outputPer1M: 2.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "featherless-ai",
        status: "live",
      },
      {
        provider: "fireworks-ai",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.4,
        outputPer1M: 4.4,
        supportsTools: true,
        supportsStructuredOutput: true,
      },
      {
        provider: "novita",
        status: "live",
        contextLength: 1048576,
        inputPer1M: 1.4,
        outputPer1M: 4.4,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "scaleway",
        status: "live",
        inputPer1M: 2.052,
        outputPer1M: 6.27,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "together",
        status: "live",
        contextLength: 1048575,
        inputPer1M: 1.4,
        outputPer1M: 4.4,
        supportsTools: true,
        supportsStructuredOutput: false,
      },
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
  "zai-org/GLM-5.2-FP8": {
    wireId: "zai-org/GLM-5.2-FP8",
    providers: [
      {
        provider: "zai-org",
        status: "live",
        supportsTools: true,
        supportsStructuredOutput: false,
      }
    ],
  },
}
