// AUTO-GENERATED by @agentproto/catalog-sync (llm:opencode-go).
// Do not edit by hand — re-run `pnpm --filter @agentproto/catalog-sync generate`.
// Source: https://models.dev/api.json (provider "opencode-go" — OpenCode Go)
// Prices come VERBATIM from the source's cost.input / cost.output, which
// models.dev already publishes as USD per 1M tokens (no per-token
// conversion, unlike the Requesty table). cacheReadMultiplier /
// cacheWriteMultiplier are cost.cache_read / cost.cache_write expressed
// relative to cost.input, and are omitted when the base input price is 0
// (every `-free` variant) because a free model has no cache discount.
// Zero-priced models are KEPT — on these endpoints zero is the truth, not
// a missing price.
// Keys are `<provider>/<bare-id>`, the form opencode's own config uses and
// the form the runtime derives the billing endpoint from; `vendor` is a
// heuristic attribution of the model's BUILDER and is metadata only.
// addedAt is the ISO date this id was first seen by a sync run — backfilled
// from the source's own `release_date`, then NEVER mutated; see
// packages/catalog-sync/src/added-at.ts and the package README.

import type { LLMPricing } from "./catalog.js"

export const OPENCODE_GO_ROUTES: Record<string, LLMPricing> = {
  "opencode-go/deepseek-v4-flash": {
    inputPer1M: 0.15,
    outputPer1M: 0.6,
    cacheReadMultiplier: 0.02,
    addedAt: "2026-07-31",
    vendor: "deepseek",
    provider: "opencode-go",
  },
  "opencode-go/deepseek-v4-flash-vision-exp": {
    inputPer1M: 0.15,
    outputPer1M: 0.6,
    cacheReadMultiplier: 0.02,
    addedAt: "2026-08-21",
    vendor: "deepseek",
    provider: "opencode-go",
  },
  "opencode-go/deepseek-v4-pro": {
    inputPer1M: 0.66,
    outputPer1M: 1.98,
    cacheReadMultiplier: 0.033333,
    addedAt: "2026-04-24",
    vendor: "deepseek",
    provider: "opencode-go",
  },
  "opencode-go/deepseek-v4.1-flash": {
    inputPer1M: 0.15,
    outputPer1M: 0.6,
    cacheReadMultiplier: 0.02,
    addedAt: "2026-09-10",
    vendor: "deepseek",
    provider: "opencode-go",
  },
  "opencode-go/glm-5": {
    inputPer1M: 1,
    outputPer1M: 3.2,
    cacheReadMultiplier: 0.2,
    addedAt: "2026-02-11",
    vendor: "z-ai",
    provider: "opencode-go",
  },
  "opencode-go/glm-5.1": {
    inputPer1M: 1.4,
    outputPer1M: 4.4,
    cacheReadMultiplier: 0.185714,
    addedAt: "2026-04-07",
    vendor: "z-ai",
    provider: "opencode-go",
  },
  "opencode-go/glm-5.2": {
    inputPer1M: 1.4,
    outputPer1M: 4.4,
    cacheReadMultiplier: 0.185714,
    addedAt: "2026-06-13",
    vendor: "z-ai",
    provider: "opencode-go",
  },
  "opencode-go/glm-5.3": {
    inputPer1M: 1.4,
    outputPer1M: 4.4,
    cacheReadMultiplier: 0.185714,
    addedAt: "2026-08-14",
    vendor: "z-ai",
    provider: "opencode-go",
  },
  "opencode-go/glm-5.3-flash": {
    inputPer1M: 0.15,
    outputPer1M: 0.5,
    cacheReadMultiplier: 0.2,
    addedAt: "2026-08-26",
    vendor: "z-ai",
    provider: "opencode-go",
  },
  "opencode-go/gpt-5.6-luna": {
    inputPer1M: 0.2,
    outputPer1M: 1.2,
    cacheReadMultiplier: 0.1,
    cacheWriteMultiplier: 1.25,
    addedAt: "2026-07-09",
    vendor: "openai",
    provider: "opencode-go",
  },
  "opencode-go/grok-4.5": {
    inputPer1M: 2,
    outputPer1M: 6,
    cacheReadMultiplier: 0.15,
    addedAt: "2026-07-08",
    vendor: "x-ai",
    provider: "opencode-go",
  },
  "opencode-go/grok-4.6": {
    inputPer1M: 2,
    outputPer1M: 6,
    cacheReadMultiplier: 0.25,
    addedAt: "2026-08-12",
    vendor: "x-ai",
    provider: "opencode-go",
  },
  "opencode-go/hy3": {
    inputPer1M: 0.14,
    outputPer1M: 0.58,
    cacheReadMultiplier: 0.25,
    addedAt: "2026-07-06",
    vendor: "tencent",
    provider: "opencode-go",
  },
  "opencode-go/hy4-preview": {
    inputPer1M: 0.834,
    outputPer1M: 2.501,
    cacheReadMultiplier: 0.05036,
    addedAt: "2026-08-28",
    vendor: "tencent",
    provider: "opencode-go",
  },
  "opencode-go/kimi-k2.5": {
    inputPer1M: 0.6,
    outputPer1M: 3,
    cacheReadMultiplier: 0.166667,
    addedAt: "2026-01-27",
    vendor: "moonshotai",
    provider: "opencode-go",
  },
  "opencode-go/kimi-k2.6": {
    inputPer1M: 0.95,
    outputPer1M: 4,
    cacheReadMultiplier: 0.168421,
    addedAt: "2026-04-21",
    vendor: "moonshotai",
    provider: "opencode-go",
  },
  "opencode-go/kimi-k2.7-code": {
    inputPer1M: 0.95,
    outputPer1M: 4,
    cacheReadMultiplier: 0.2,
    addedAt: "2026-06-12",
    vendor: "moonshotai",
    provider: "opencode-go",
  },
  "opencode-go/kimi-k3": {
    inputPer1M: 3,
    outputPer1M: 15,
    cacheReadMultiplier: 0.1,
    addedAt: "2026-07-16",
    vendor: "moonshotai",
    provider: "opencode-go",
  },
  "opencode-go/longcat-2.0": {
    inputPer1M: 0.3,
    outputPer1M: 1.2,
    cacheReadMultiplier: 0.02,
    addedAt: "2026-06-30",
    vendor: "meituan",
    provider: "opencode-go",
  },
  "opencode-go/mimo-v2-omni": {
    inputPer1M: 0.4,
    outputPer1M: 2,
    cacheReadMultiplier: 0.2,
    addedAt: "2026-03-18",
    vendor: "xiaomi",
    provider: "opencode-go",
  },
  "opencode-go/mimo-v2-pro": {
    inputPer1M: 1,
    outputPer1M: 3,
    cacheReadMultiplier: 0.2,
    addedAt: "2026-03-18",
    vendor: "xiaomi",
    provider: "opencode-go",
  },
  "opencode-go/mimo-v2.5": {
    inputPer1M: 0.14,
    outputPer1M: 0.28,
    cacheReadMultiplier: 0.02,
    addedAt: "2026-04-22",
    vendor: "xiaomi",
    provider: "opencode-go",
  },
  "opencode-go/mimo-v2.5-pro": {
    inputPer1M: 0.435,
    outputPer1M: 0.87,
    cacheReadMultiplier: 0.008333,
    addedAt: "2026-04-22",
    vendor: "xiaomi",
    provider: "opencode-go",
  },
  "opencode-go/minimax-m2.5": {
    inputPer1M: 0.3,
    outputPer1M: 1.2,
    cacheReadMultiplier: 0.1,
    addedAt: "2026-02-12",
    vendor: "minimax",
    provider: "opencode-go",
  },
  "opencode-go/minimax-m2.7": {
    inputPer1M: 0.3,
    outputPer1M: 1.2,
    cacheReadMultiplier: 0.2,
    addedAt: "2026-03-18",
    vendor: "minimax",
    provider: "opencode-go",
  },
  "opencode-go/minimax-m3": {
    inputPer1M: 0.3,
    outputPer1M: 1.2,
    cacheReadMultiplier: 0.2,
    addedAt: "2026-05-31",
    vendor: "minimax",
    provider: "opencode-go",
  },
  "opencode-go/muse-spark-1.2-contributor": {
    inputPer1M: 0.1,
    outputPer1M: 0.2,
    cacheReadMultiplier: 0.02,
    addedAt: "2026-08-05",
    vendor: "meta",
    provider: "opencode-go",
  },
  "opencode-go/muse-spark-1.3-contributor": {
    inputPer1M: 0.1,
    outputPer1M: 0.2,
    cacheReadMultiplier: 0.02,
    addedAt: "2026-09-02",
    vendor: "meta",
    provider: "opencode-go",
  },
  "opencode-go/omen-alpha": {
    inputPer1M: 0.2,
    outputPer1M: 0.66,
    cacheReadMultiplier: 0.2,
    addedAt: "2026-09-04",
    vendor: "opencode",
    provider: "opencode-go",
  },
  "opencode-go/ox-alpha-free": {
    inputPer1M: 0,
    outputPer1M: 0,
    addedAt: "2026-08-21",
    vendor: "opencode",
    provider: "opencode-go",
  },
  "opencode-go/qwen3.5-plus": {
    inputPer1M: 0.2,
    outputPer1M: 1.2,
    cacheReadMultiplier: 0.1,
    cacheWriteMultiplier: 1.25,
    addedAt: "2026-02-16",
    vendor: "qwen",
    provider: "opencode-go",
  },
  "opencode-go/qwen3.6-plus": {
    inputPer1M: 0.5,
    outputPer1M: 3,
    cacheReadMultiplier: 0.1,
    cacheWriteMultiplier: 1.25,
    addedAt: "2026-04-02",
    vendor: "qwen",
    provider: "opencode-go",
  },
  "opencode-go/qwen3.7-max": {
    inputPer1M: 2.5,
    outputPer1M: 7.5,
    cacheReadMultiplier: 0.2,
    cacheWriteMultiplier: 1.25,
    addedAt: "2026-05-21",
    vendor: "qwen",
    provider: "opencode-go",
  },
  "opencode-go/qwen3.7-plus": {
    inputPer1M: 0.4,
    outputPer1M: 1.6,
    cacheReadMultiplier: 0.1,
    cacheWriteMultiplier: 1.25,
    addedAt: "2026-06-02",
    vendor: "qwen",
    provider: "opencode-go",
  },
  "opencode-go/qwen3.8-flash": {
    inputPer1M: 0.15,
    outputPer1M: 0.47,
    cacheReadMultiplier: 0.106667,
    cacheWriteMultiplier: 1.333333,
    addedAt: "2026-08-26",
    vendor: "qwen",
    provider: "opencode-go",
  },
  "opencode-go/qwen3.8-max": {
    inputPer1M: 2,
    outputPer1M: 6,
    cacheReadMultiplier: 0.125,
    cacheWriteMultiplier: 1.25,
    addedAt: "2026-08-03",
    vendor: "qwen",
    provider: "opencode-go",
  },
}

/**
 * BARE ids on OpenCode Go whose wire surface is the Anthropic Messages
 * API — the source's `provider.npm === "@ai-sdk/anthropic"`. These are the
 * ONLY ids reachable through the Anthropic-compatible gateway preset of the
 * same name (claude-code / claude-sdk); the rest of the endpoint's lineup
 * speaks OpenAI chat/completions or the OpenAI Responses API and has to go
 * through the opencode adapter instead. Bare (not `<provider>/<id>`) because
 * that is what an Anthropic client puts in `ANTHROPIC_MODEL` / on the wire.
 */
export const OPENCODE_GO_ANTHROPIC_MODELS: readonly string[] = [
  "minimax-m2.5",
  "minimax-m2.7",
  "minimax-m3",
  "qwen3.8-flash",
]
