// GENERATED FILE — do not edit; regenerate with scripts/catalog-sync/sync-openai.mjs (data: OpenRouter passthrough — OpenAI has NO native models/pricing endpoint, see packages/catalog-sync/src/sources/openai.ts, synced 2026-08-31T13:08:57.175Z)
//
// ⚠ These prices are OpenRouter's rates, NOT the official
// openai.com/api/pricing page. OpenAI publishes no stable machine-readable
// models/pricing endpoint, so OpenRouter passthrough is the only automated
// source for both ids and prices; OpenRouter rates may differ from
// OpenAI's first-party pricing.

export const OPENAI_GENERATED_PRICING = {
  "gpt-3.5-turbo": { inputPer1M: 0.5, outputPer1M: 1.5, vendor: "openai", provider: "openai" },
  "gpt-3.5-turbo-0613": { inputPer1M: 1, outputPer1M: 2, vendor: "openai", provider: "openai" },
  "gpt-3.5-turbo-16k": { inputPer1M: 3, outputPer1M: 4, vendor: "openai", provider: "openai" },
  "gpt-3.5-turbo-instruct": { inputPer1M: 1.5, outputPer1M: 2, vendor: "openai", provider: "openai" },
  "gpt-4": { inputPer1M: 30, outputPer1M: 60, vendor: "openai", provider: "openai" },
  "gpt-4-turbo": { inputPer1M: 10, outputPer1M: 30, vendor: "openai", provider: "openai" },
  "gpt-4-turbo-preview": { inputPer1M: 10, outputPer1M: 30, vendor: "openai", provider: "openai" },
  "gpt-4.1": { inputPer1M: 2, outputPer1M: 8, cacheReadMultiplier: 0.25, vendor: "openai", provider: "openai" },
  "gpt-4.1-mini": { inputPer1M: 0.4, outputPer1M: 1.6, cacheReadMultiplier: 0.25, vendor: "openai", provider: "openai" },
  "gpt-4.1-nano": { inputPer1M: 0.1, outputPer1M: 0.4, cacheReadMultiplier: 0.25, vendor: "openai", provider: "openai" },
  "gpt-4o": { inputPer1M: 2.5, outputPer1M: 10, cacheReadMultiplier: 0.5, vendor: "openai", provider: "openai" },
  "gpt-4o-2024-05-13": { inputPer1M: 5, outputPer1M: 15, vendor: "openai", provider: "openai" },
  "gpt-4o-2024-08-06": { inputPer1M: 2.5, outputPer1M: 10, cacheReadMultiplier: 0.5, vendor: "openai", provider: "openai" },
  "gpt-4o-2024-11-20": { inputPer1M: 2.5, outputPer1M: 10, cacheReadMultiplier: 0.5, vendor: "openai", provider: "openai" },
  "gpt-4o-mini": { inputPer1M: 0.15, outputPer1M: 0.6, cacheReadMultiplier: 0.5, vendor: "openai", provider: "openai" },
  "gpt-4o-mini-2024-07-18": { inputPer1M: 0.15, outputPer1M: 0.6, cacheReadMultiplier: 0.5, vendor: "openai", provider: "openai" },
  "gpt-5": { inputPer1M: 1.25, outputPer1M: 10, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5-image": { inputPer1M: 10, outputPer1M: 10, cacheReadMultiplier: 0.125, vendor: "openai", provider: "openai" },
  "gpt-5-image-mini": { inputPer1M: 2.5, outputPer1M: 2, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5-mini": { inputPer1M: 0.25, outputPer1M: 2, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5-nano": { inputPer1M: 0.05, outputPer1M: 0.4, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5-pro": { inputPer1M: 15, outputPer1M: 120, vendor: "openai", provider: "openai" },
  "gpt-5.1": { inputPer1M: 1.25, outputPer1M: 10, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.1-codex": { inputPer1M: 1.25, outputPer1M: 10, cacheReadMultiplier: 0.104, vendor: "openai", provider: "openai" },
  "gpt-5.1-codex-max": { inputPer1M: 1.25, outputPer1M: 10, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.1-codex-mini": { inputPer1M: 0.25, outputPer1M: 2, cacheReadMultiplier: 0.12, vendor: "openai", provider: "openai" },
  "gpt-5.2": { inputPer1M: 1.75, outputPer1M: 14, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.2-chat": { inputPer1M: 1.75, outputPer1M: 14, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.2-codex": { inputPer1M: 1.75, outputPer1M: 14, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.2-pro": { inputPer1M: 21, outputPer1M: 168, vendor: "openai", provider: "openai" },
  "gpt-5.3-codex": { inputPer1M: 1.75, outputPer1M: 14, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.4": { inputPer1M: 2.5, outputPer1M: 15, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.4-mini": { inputPer1M: 0.75, outputPer1M: 4.5, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.4-nano": { inputPer1M: 0.2, outputPer1M: 1.25, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.4-pro": { inputPer1M: 30, outputPer1M: 180, vendor: "openai", provider: "openai" },
  "gpt-5.5": { inputPer1M: 5, outputPer1M: 30, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-5.5-pro": { inputPer1M: 30, outputPer1M: 180, vendor: "openai", provider: "openai" },
  "gpt-5.6-luna": { inputPer1M: 0.2, outputPer1M: 1.2, cacheReadMultiplier: 0.1, cacheWriteMultiplier: 1.25, vendor: "openai", provider: "openai" },
  "gpt-5.6-luna-pro": { inputPer1M: 0.2, outputPer1M: 1.2, cacheReadMultiplier: 0.1, cacheWriteMultiplier: 1.25, vendor: "openai", provider: "openai" },
  "gpt-5.6-sol": { inputPer1M: 2, outputPer1M: 10, cacheReadMultiplier: 0.1, cacheWriteMultiplier: 1.25, vendor: "openai", provider: "openai" },
  "gpt-5.6-sol-pro": { inputPer1M: 2, outputPer1M: 10, cacheReadMultiplier: 0.1, cacheWriteMultiplier: 1.25, vendor: "openai", provider: "openai" },
  "gpt-5.6-terra": { inputPer1M: 2, outputPer1M: 12, cacheReadMultiplier: 0.1, cacheWriteMultiplier: 1.25, vendor: "openai", provider: "openai" },
  "gpt-5.6-terra-pro": { inputPer1M: 2, outputPer1M: 12, cacheReadMultiplier: 0.1, cacheWriteMultiplier: 1.25, vendor: "openai", provider: "openai" },
  "gpt-audio": { inputPer1M: 2.5, outputPer1M: 10, vendor: "openai", provider: "openai" },
  "gpt-audio-mini": { inputPer1M: 0.6, outputPer1M: 2.4, vendor: "openai", provider: "openai" },
  "gpt-chat-latest": { inputPer1M: 5, outputPer1M: 30, cacheReadMultiplier: 0.1, vendor: "openai", provider: "openai" },
  "gpt-oss-120b": { inputPer1M: 0.037, outputPer1M: 0.17, vendor: "openai", provider: "openai" },
  "gpt-oss-120b:batch": { inputPer1M: 0.15, outputPer1M: 0.6, vendor: "openai", provider: "openai" },
  "gpt-oss-20b": { inputPer1M: 0.03, outputPer1M: 0.13, cacheReadMultiplier: 1, vendor: "openai", provider: "openai" },
  "gpt-oss-20b:batch": { inputPer1M: 0.05, outputPer1M: 0.2, vendor: "openai", provider: "openai" },
  "gpt-oss-safeguard-20b": { inputPer1M: 0.075, outputPer1M: 0.3, cacheReadMultiplier: 0.5, vendor: "openai", provider: "openai" },
  "o1": { inputPer1M: 15, outputPer1M: 60, cacheReadMultiplier: 0.5, vendor: "openai", provider: "openai" },
  "o1-pro": { inputPer1M: 150, outputPer1M: 600, vendor: "openai", provider: "openai" },
  "o3": { inputPer1M: 2, outputPer1M: 8, cacheReadMultiplier: 0.25, vendor: "openai", provider: "openai" },
  "o3-mini": { inputPer1M: 1.1, outputPer1M: 4.4, cacheReadMultiplier: 0.5, vendor: "openai", provider: "openai" },
  "o3-mini-high": { inputPer1M: 1.1, outputPer1M: 4.4, cacheReadMultiplier: 0.5, vendor: "openai", provider: "openai" },
  "o3-pro": { inputPer1M: 20, outputPer1M: 80, vendor: "openai", provider: "openai" },
  "o4-mini": { inputPer1M: 1.1, outputPer1M: 4.4, cacheReadMultiplier: 0.25, vendor: "openai", provider: "openai" },
  "o4-mini-high": { inputPer1M: 1.1, outputPer1M: 4.4, cacheReadMultiplier: 0.25, vendor: "openai", provider: "openai" },
} as const
