/**
 * MiniMax voices — provider-authored source for the unified voice
 * catalog. Each entry is a `CatalogVoice`: identity (`providerVoiceId`)
 * + selection metadata (label, description, gender, languages, featured).
 *
 * `catalogId`s are derived (`<provider>-<slug(providerVoiceId)>`) and
 * materialized as literals so the `CatalogVoiceId` union stays
 * autocomplete-able. Legacy `simone-N` slugs are preserved in `aliases`.
 * Authored per-provider; `VOICE_CATALOG` concatenates every provider.
 */

import type { CatalogVoice } from "../../schema/voice.js"

const LANGS = [
  "en",
  "fr",
  "es",
  "de",
  "it",
  "pt",
  "ja",
  "ko",
  "zh",
  "ar",
  "ru",
  "tr",
  "nl",
  "pl",
  "sv",
  "da",
  "no",
  "fi",
  "hi",
  "th",
  "vi",
  "id",
  "ms",
  "tl",
  "ro",
  "hu",
]

export const MINIMAX_VOICES = [
  {
    catalogId: "minimax-french-female-anchor",
    providerVoiceId: "French_FemaleAnchor",
    provider: "minimax",
    label: "Camille",
    description: "Posée et professionnelle, style présentatrice",
    gender: "female",
    primaryLanguage: "fr",
    supportedLanguages: LANGS,
    aliases: ["simone-2"],
    age: "adult",
    quality: "premium",
    featured: true,
  },
  {
    catalogId: "minimax-french-movie-lead-female",
    providerVoiceId: "French_MovieLeadFemale",
    provider: "minimax",
    label: "Sophie",
    description: "Chaleureuse et naturelle, style cinéma",
    gender: "female",
    primaryLanguage: "fr",
    supportedLanguages: LANGS,
    aliases: ["simone-3"],
    age: "adult",
    quality: "premium",
    featured: true,
  },
  {
    catalogId: "minimax-french-female-news-anchor",
    providerVoiceId: "French_Female_News Anchor",
    provider: "minimax",
    label: "Marion",
    description: "Rapide et dynamique, style journaliste",
    gender: "female",
    primaryLanguage: "fr",
    supportedLanguages: LANGS,
    aliases: ["simone-4"],
    age: "adult",
    quality: "premium",
    featured: true,
  },
  {
    catalogId: "minimax-french-male-narrator",
    providerVoiceId: "French_MaleNarrator",
    provider: "minimax",
    label: "Pierre",
    description: "Voix masculine posée, style narrateur",
    gender: "male",
    primaryLanguage: "fr",
    supportedLanguages: LANGS,
    aliases: ["simone-5"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-french-male-speech-new",
    providerVoiceId: "French_Male_Speech_New",
    provider: "minimax",
    label: "Antoine",
    description: "Voix masculine calme et mesurée",
    gender: "male",
    primaryLanguage: "fr",
    supportedLanguages: LANGS,
    aliases: ["simone-6"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-french-casual-man",
    providerVoiceId: "French_CasualMan",
    provider: "minimax",
    label: "Lucas",
    description: "Voix masculine décontractée",
    gender: "male",
    primaryLanguage: "fr",
    supportedLanguages: LANGS,
    aliases: ["simone-7"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-trustworth-man",
    providerVoiceId: "English_Trustworth_Man",
    provider: "minimax",
    label: "Aaron",
    description: "Trustworthy adult male voice",
    gender: "male",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-8"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-calm-woman",
    providerVoiceId: "English_CalmWoman",
    provider: "minimax",
    label: "Olivia",
    description: "Calm adult female voice",
    gender: "female",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-9"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-gentle-voiced-man",
    providerVoiceId: "English_Gentle-voiced_man",
    provider: "minimax",
    label: "Mark",
    description: "Gentle adult male voice",
    gender: "male",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-10"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-graceful-lady",
    providerVoiceId: "English_Graceful_Lady",
    provider: "minimax",
    label: "Charlotte",
    description: "Graceful adult female voice",
    gender: "female",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-11"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-upbeat-woman",
    providerVoiceId: "English_Upbeat_Woman",
    provider: "minimax",
    label: "Emma",
    description: "Upbeat young female voice",
    gender: "female",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-12"],
    age: "young",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-man-with-deep-voice",
    providerVoiceId: "English_ManWithDeepVoice",
    provider: "minimax",
    label: "Henry",
    description: "Deep adult male voice",
    gender: "male",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-13"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-serene-woman",
    providerVoiceId: "English_SereneWoman",
    provider: "minimax",
    label: "Hannah",
    description: "Serene adult female voice",
    gender: "female",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-14"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-confident-woman",
    providerVoiceId: "English_ConfidentWoman",
    provider: "minimax",
    label: "Grace",
    description: "Confident adult female voice",
    gender: "female",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-15"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-patient-man",
    providerVoiceId: "English_PatientMan",
    provider: "minimax",
    label: "Patrick",
    description: "Patient adult male voice",
    gender: "male",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-16"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-expressive-narrator",
    providerVoiceId: "English_expressive_narrator",
    provider: "minimax",
    label: "Daniel",
    description: "Expressive adult male narrator",
    gender: "male",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-17"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-english-radiant-girl",
    providerVoiceId: "English_radiant_girl",
    provider: "minimax",
    label: "Ruby",
    description: "Radiant young female voice",
    gender: "female",
    primaryLanguage: "en",
    supportedLanguages: LANGS,
    aliases: ["simone-18"],
    age: "young",
    quality: "premium",
  },
  {
    catalogId: "minimax-spanish-serene-woman",
    providerVoiceId: "Spanish_SereneWoman",
    provider: "minimax",
    label: "Isabel",
    description: "Serene adult female voice",
    gender: "female",
    primaryLanguage: "es",
    supportedLanguages: LANGS,
    aliases: ["simone-19"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-spanish-narrator",
    providerVoiceId: "Spanish_Narrator",
    provider: "minimax",
    label: "Diego",
    description: "Adult male narrator voice",
    gender: "male",
    primaryLanguage: "es",
    supportedLanguages: LANGS,
    aliases: ["simone-20"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-german-friendly-man",
    providerVoiceId: "German_FriendlyMan",
    provider: "minimax",
    label: "Klaus",
    description: "Friendly adult male voice",
    gender: "male",
    primaryLanguage: "de",
    supportedLanguages: LANGS,
    aliases: ["simone-21"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-german-sweet-lady",
    providerVoiceId: "German_SweetLady",
    provider: "minimax",
    label: "Greta",
    description: "Sweet young female voice",
    gender: "female",
    primaryLanguage: "de",
    supportedLanguages: LANGS,
    aliases: ["simone-22"],
    age: "young",
    quality: "premium",
  },
  {
    catalogId: "minimax-japanese-gentle-butler",
    providerVoiceId: "Japanese_GentleButler",
    provider: "minimax",
    label: "Haruto",
    description: "Gentle adult male voice",
    gender: "male",
    primaryLanguage: "ja",
    supportedLanguages: LANGS,
    aliases: ["simone-23"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-japanese-kind-lady",
    providerVoiceId: "Japanese_KindLady",
    provider: "minimax",
    label: "Yuki",
    description: "Kind adult female voice",
    gender: "female",
    primaryLanguage: "ja",
    supportedLanguages: LANGS,
    aliases: ["simone-24"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-korean-calm-gentleman",
    providerVoiceId: "Korean_CalmGentleman",
    provider: "minimax",
    label: "Minjun",
    description: "Calm adult male voice",
    gender: "male",
    primaryLanguage: "ko",
    supportedLanguages: LANGS,
    aliases: ["simone-25"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-korean-sweet-girl",
    providerVoiceId: "Korean_SweetGirl",
    provider: "minimax",
    label: "Yuna",
    description: "Sweet young female voice",
    gender: "female",
    primaryLanguage: "ko",
    supportedLanguages: LANGS,
    aliases: ["simone-26"],
    age: "young",
    quality: "premium",
  },
  {
    catalogId: "minimax-chinese-mandarin-gentleman",
    providerVoiceId: "Chinese (Mandarin)_Gentleman",
    provider: "minimax",
    label: "Wei",
    description: "Adult male voice",
    gender: "male",
    primaryLanguage: "zh",
    supportedLanguages: LANGS,
    aliases: ["simone-27"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-chinese-mandarin-sweet-lady",
    providerVoiceId: "Chinese (Mandarin)_Sweet_Lady",
    provider: "minimax",
    label: "Mei",
    description: "Sweet young female voice",
    gender: "female",
    primaryLanguage: "zh",
    supportedLanguages: LANGS,
    aliases: ["simone-28"],
    age: "young",
    quality: "premium",
  },
  {
    catalogId: "minimax-portuguese-reliable-man",
    providerVoiceId: "Portuguese_ReliableMan",
    provider: "minimax",
    label: "Rafael",
    description: "Reliable adult male voice",
    gender: "male",
    primaryLanguage: "pt",
    supportedLanguages: LANGS,
    aliases: ["simone-29"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-portuguese-sweet-girl",
    providerVoiceId: "Portuguese_SweetGirl",
    provider: "minimax",
    label: "Beatriz",
    description: "Sweet young female voice",
    gender: "female",
    primaryLanguage: "pt",
    supportedLanguages: LANGS,
    aliases: ["simone-30"],
    age: "young",
    quality: "premium",
  },
  {
    catalogId: "minimax-italian-narrator",
    providerVoiceId: "Italian_Narrator",
    provider: "minimax",
    label: "Marco",
    description: "Adult male narrator voice",
    gender: "male",
    primaryLanguage: "it",
    supportedLanguages: LANGS,
    aliases: ["simone-31"],
    age: "adult",
    quality: "premium",
  },
  {
    catalogId: "minimax-italian-brave-heroine",
    providerVoiceId: "Italian_BraveHeroine",
    provider: "minimax",
    label: "Giulia",
    description: "Brave adult female voice",
    gender: "female",
    primaryLanguage: "it",
    supportedLanguages: LANGS,
    aliases: ["simone-32"],
    age: "adult",
    quality: "premium",
  },
] as const satisfies readonly CatalogVoice[]
