// GENERATED by @agentproto/catalog-sync (voice previews) — do not edit.
// Pre-baked voice-preview samples on the org public bucket. Maps each
// curated voice to the UI locales it has a sample for, so the catalog can
// attach `samplePath` and the picker can play a static WAV instead of
// synthesizing per request.

export const VOICE_PREVIEW_BASE =
  "https://storage.googleapis.com/agentik-public-assets/voice-previews"

export const VOICE_PREVIEW_LOCALES = ["en","fr","es","de","it","pt"] as const

/** catalogId → UI locales that have a baked sample. */
export const BAKED_VOICE_PREVIEWS: Record<string, readonly string[]> = {
  "elevenlabs-alice": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "elevenlabs-daniel": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "elevenlabs-george": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "elevenlabs-nicolas": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "elevenlabs-sarah": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "elevenlabs-victoria": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "gemini-live-aoede": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "gemini-live-charon": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "gemini-live-fenrir": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "gemini-live-kore": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "gemini-live-puck": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-chinese-mandarin-gentleman": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-chinese-mandarin-sweet-lady": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-calm-woman": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-confident-woman": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-expressive-narrator": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-gentle-voiced-man": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-graceful-lady": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-man-with-deep-voice": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-patient-man": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-radiant-girl": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-serene-woman": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-trustworth-man": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-english-upbeat-woman": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-french-casual-man": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-french-female-anchor": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-french-female-news-anchor": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-french-male-narrator": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-french-male-speech-new": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-french-movie-lead-female": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-german-friendly-man": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-german-sweet-lady": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-italian-brave-heroine": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-italian-narrator": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-japanese-gentle-butler": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-japanese-kind-lady": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-korean-calm-gentleman": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-korean-sweet-girl": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-portuguese-reliable-man": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-portuguese-sweet-girl": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-spanish-narrator": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "minimax-spanish-serene-woman": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-alloy": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-ash": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-ballad": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-cedar": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-coral": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-echo": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-marin": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-sage": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-shimmer": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "openai-realtime-verse": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ],
  "elevenlabs-victoire": [
    "en",
    "fr",
    "es",
    "de",
    "it",
    "pt"
  ]
}

/**
 * Public URL of a voice's baked sample in `locale` (falling back to en,
 * then any baked locale), or `undefined` if the voice has no sample —
 * in which case the caller should synthesize on demand.
 */
export function voicePreviewUrl(
  catalogId: string,
  locale = "en"
): string | undefined {
  const locales = BAKED_VOICE_PREVIEWS[catalogId]
  if (!locales || locales.length === 0) return undefined
  const chosen = locales.includes(locale)
    ? locale
    : locales.includes("en")
      ? "en"
      : locales[0]
  return `${VOICE_PREVIEW_BASE}/${catalogId}.${chosen}.wav`
}
