/**
 * Install `chrome-devtools-mcp` into a dedicated, plugin-owned dir
 * (`~/.agentproto/chrome-mcp/` by default) so the daemon's MCP proxy
 * can spawn it by absolute bin path. This sidesteps a known issue
 * where running the daemon via `npm exec @agentproto/cli@latest` and
 * then having its proxy spawn another `npx chrome-devtools-mcp@latest`
 * confuses the nested npm-exec (`sh: chrome-devtools-mcp@latest:
 * command not found`).
 *
 * Why a dedicated dir instead of a global install:
 *   - No sudo needed, no PATH conflict with the user's other tooling.
 *   - Plugin owns its dependency lifecycle — `remove` cleans it up.
 *   - Version pinning is per-plugin (a future profile could pin a
 *     different chrome-devtools-mcp without affecting anything else).
 *
 * The dir doubles as an opaque marker that the plugin is "installed";
 * `setup()` calls this idempotently so re-runs are safe.
 */

import { spawn } from "node:child_process"
import { promises as fs } from "node:fs"
import { homedir } from "node:os"
import { join } from "node:path"

export const DEFAULT_CHROME_MCP_PREFIX = (home: string = homedir()): string =>
  join(home, ".agentproto", "chrome-mcp")

export interface InstallOptions {
  /** Target directory for the npm install. Default
   *  `~/.agentproto/chrome-mcp`. */
  prefix?: string
  /** chrome-devtools-mcp version (npm spec). Default `latest`. */
  version?: string
  /** Override the npm executable (test/CI). Default `npm` from PATH. */
  npm?: string
  /** Progress callback fired on each non-empty stderr/stdout chunk so
   *  the CLI can stream "Downloading chrome-devtools-mcp..." etc. */
  onProgress?: (line: string) => void
}

export interface InstallResult {
  /** Where the install landed. */
  prefix: string
  /** Absolute path to the `chrome-devtools-mcp` binary symlink in
   *  `<prefix>/node_modules/.bin/`. */
  binPath: string
  /** Version actually installed, read back from the package lockfile. */
  installedVersion: string
}

/**
 * Idempotent: re-running with the same version is a no-op for npm,
 * and re-running with a different version migrates in-place.
 */
export async function installChromeMcp(
  opts: InstallOptions = {}
): Promise<InstallResult> {
  const prefix = opts.prefix ?? DEFAULT_CHROME_MCP_PREFIX()
  const version = opts.version ?? "latest"
  const npm = opts.npm ?? "npm"

  await fs.mkdir(prefix, { recursive: true })
  // npm install --prefix requires a package.json at the target.
  const pkgJsonPath = join(prefix, "package.json")
  try {
    await fs.access(pkgJsonPath)
  } catch {
    await fs.writeFile(
      pkgJsonPath,
      JSON.stringify(
        {
          name: "agentproto-chrome-mcp-prefix",
          private: true,
          description:
            "Auto-generated by @agentproto/plugin-local-browser. Holds the chrome-devtools-mcp dependency the daemon's MCP proxy spawns. Safe to delete — re-run `agentproto-browser setup` to recreate.",
        },
        null,
        2
      ) + "\n"
    )
  }

  await runNpm(
    npm,
    ["install", `chrome-devtools-mcp@${version}`, "--no-fund", "--no-audit"],
    prefix,
    opts.onProgress
  )

  const binPath = join(prefix, "node_modules", ".bin", "chrome-devtools-mcp")
  await fs.access(binPath).catch(() => {
    throw new Error(
      `install: npm install finished but no bin at ${binPath}. ` +
        `Did chrome-devtools-mcp change its package layout?`
    )
  })

  // Read the installed version back from the package's own
  // package.json — more reliable than re-parsing the npm-install
  // output which has 5+ format variants across npm versions.
  const installedPkgPath = join(
    prefix,
    "node_modules",
    "chrome-devtools-mcp",
    "package.json"
  )
  let installedVersion = "(unknown)"
  try {
    const raw = await fs.readFile(installedPkgPath, "utf8")
    const parsed = JSON.parse(raw) as { version?: unknown }
    if (typeof parsed.version === "string") installedVersion = parsed.version
  } catch {
    // Non-fatal: caller only uses the version for display.
  }

  return { prefix, binPath, installedVersion }
}

function runNpm(
  npm: string,
  args: readonly string[],
  cwd: string,
  onProgress?: (line: string) => void
): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(npm, [...args], {
      cwd,
      stdio: ["ignore", "pipe", "pipe"],
      // shell:false — args are passed verbatim, no expansion. We
      // deliberately avoid npx here; the whole point of this module
      // is to install once and resolve by absolute path forever after.
      shell: false,
    })
    const stderrBuf: string[] = []
    const tail = (chunk: Buffer | string): void => {
      const line = typeof chunk === "string" ? chunk : chunk.toString("utf8")
      stderrBuf.push(line)
      if (stderrBuf.length > 40) stderrBuf.shift()
      const trimmed = line.trim()
      if (trimmed) onProgress?.(trimmed)
    }
    child.stdout?.on("data", tail)
    child.stderr?.on("data", tail)
    child.on("error", err => reject(err))
    child.on("close", code => {
      if (code === 0) {
        resolve()
        return
      }
      reject(
        new Error(
          `npm install exited ${code}.\n` +
            `  cwd: ${cwd}\n` +
            `  args: ${args.join(" ")}\n` +
            `  last output:\n${stderrBuf.join("").slice(-1000)}`
        )
      )
    })
  })
}
