/**
 * Publishing-pipeline helpers shared by `agentproto catalog build`
 * (`packages/cli`) and the `catalog:first-party` sync script
 * (`packages/runtime/scripts/sync-first-party-catalog.mjs`): sorting +
 * merging catalog entries, and rendering the embedded first-party
 * catalog TypeScript file. Single source of truth -- no copies.
 */

import { CATALOG_SCHEMA_V1, type AppCatalogEntry } from "./app-catalog.js"

/** A v1 catalog document as published at `DEFAULT_CATALOG_SOURCE_URL`. */
export interface CatalogDocument {
  schema: string
  generatedAt: string
  entries: AppCatalogEntry[]
}

/** Entries sorted by `appId` (stable order for deterministic output). */
export function sortCatalogEntries(
  entries: readonly AppCatalogEntry[],
): AppCatalogEntry[] {
  return [...entries].sort((a, b) => (a.appId < b.appId ? -1 : a.appId > b.appId ? 1 : 0))
}

/** Build a v1 catalog document with deterministic entry order. */
export function buildCatalogDocument(
  entries: readonly AppCatalogEntry[],
  generatedAt: string,
): CatalogDocument {
  return { schema: CATALOG_SCHEMA_V1, generatedAt, entries: sortCatalogEntries(entries) }
}

/** JSON serialization used for every published catalog file (2-space
 *  indent, trailing newline) so diffs stay clean. */
export function serializeCatalogDocument(doc: CatalogDocument): string {
  return JSON.stringify(doc, null, 2) + "\n"
}

export interface MergeCatalogResult {
  entries: AppCatalogEntry[]
  /** `appId -> reason` for incoming entries that were NOT applied. */
  skipped: Map<string, string>
}

/**
 * Merge incoming entries over `base` by `appId`: the incoming entry replaces
 * the existing one when its version is >= (per `compareCatalogVersions`;
 * unparseable versions always let the incoming entry win). An incoming
 * entry with a LOWER version is skipped with a warning and the existing
 * entry stays. Incoming entries with a version that ties or is unparseable
 * replace too -- publishing the same version twice is a no-op rewrite.
 */
export function mergeCatalogEntries(
  base: readonly AppCatalogEntry[],
  incoming: readonly AppCatalogEntry[],
  compare: (a: string, b: string) => number | undefined,
): MergeCatalogResult {
  const byAppId = new Map<string, AppCatalogEntry>()
  for (const e of base) byAppId.set(e.appId, e)
  const skipped = new Map<string, string>()
  for (const e of incoming) {
    const existing = byAppId.get(e.appId)
    if (existing === undefined) {
      byAppId.set(e.appId, e)
      continue
    }
    const ev = existing.version
    const nv = e.version
    if (ev !== undefined && nv !== undefined) {
      const cmp = compare(nv, ev)
      if (cmp !== undefined && cmp < 0) {
        skipped.set(
          e.appId,
          `version ${nv} is older than the existing ${ev}; keeping the existing entry`,
        )
        continue
      }
    }
    byAppId.set(e.appId, e)
  }
  return { entries: [...byAppId.values()], skipped }
}

/**
 * Render the embedded first-party catalog TypeScript file. The emitted
 * source must pass typecheck and lint as-is: entries are serialized as
 * plain literals (key order preserved from the validated entry).
 */
export function renderFirstPartyCatalogTs(
  entries: readonly AppCatalogEntry[],
): string {
  const body = sortCatalogEntries(entries)
    .map((e) => "  " + JSON.stringify(e, null, 2).replace(/\n/g, "\n  ") + ",")
    .join("\n")
  return `/**
 * Embedded first-party catalog -- the offline fallback for the DEFAULT
 * catalog source (\`DEFAULT_CATALOG_SOURCE_URL\`, app-catalog.ts) when it is
 * unreachable and no copy of it is cached on disk, so a fresh offline
 * daemon's \`app_catalog\` still lists first-party apps. Entries carry
 * metadata + URLs: they install once the network is back.
 *
 * GENERATED by \`pnpm --filter @agentproto/runtime catalog:first-party\`
 * from the published catalog -- do not hand-edit. \`app_install {sha256}\`
 * refuses any digest mismatch.
 */

import type { AppCatalogEntry } from "./app-catalog.js"

export const FIRST_PARTY_CATALOG_ENTRIES: readonly AppCatalogEntry[] = [
${body}
]
`
}
