/**
 * Embedded first-party catalog — the offline fallback for the DEFAULT
 * catalog source (`DEFAULT_CATALOG_SOURCE_URL`, app-catalog.ts) when it is
 * unreachable and no copy of it is cached on disk, so a fresh offline
 * daemon's `app_catalog` still lists first-party apps. Entries carry
 * metadata + URLs: they install once the network is back.
 *
 * Generated by the publishing pipeline (store plan S5) from the same entries
 * it publishes. EMPTY until the first first-party bundle is published — do
 * not hand-add entries with made-up digests: `app_install {sha256}` refuses
 * any mismatch.
 */

import type { AppCatalogEntry } from "./app-catalog.js"

export const FIRST_PARTY_CATALOG_ENTRIES: readonly AppCatalogEntry[] = []
