/**
 * Quick Cloudflare Tunnel provider — zero-credential variant.
 *
 * Spawns `cloudflared tunnel --config <ours>` against an isolated
 * config file we write per-tunnel into the workspace, parses the
 * assigned `*.trycloudflare.com` URL out of cloudflared's stderr.
 * No CF account, no API token, no DNS records. Trade-off: URL is
 * ephemeral (different each run) and there's no Cloudflare Access
 * gating — auth happens at the upstream (gateway bearer token, or
 * whatever the tunneled service does for itself).
 *
 * ## Why we don't use `--url`
 *
 * `cloudflared --url http://...` synthesises an inline ingress block
 * but ALSO merges anything from `~/.cloudflared/config.yml`. If a user
 * has prior named-tunnel config there, hostname-specific rules can
 * shadow the inline rule and every request falls through to the
 * built-in `http_status:404` catch-all (the symptom: cloudflared logs
 * `ingressRule=2 originService=http_status:404` for every request,
 * origin never sees traffic). Writing our own config and passing it
 * via `--config` is hermetic — `~/.cloudflared/config.yml` is ignored
 * entirely, so the URL-forward rule always wins.
 *
 * Use this for: ad-hoc demos, "let me try this from another machine
 * for 10 minutes", iterating on the remote-MCP UX before committing
 * to a domain.
 *
 * For: persistent URLs / SSO gating, use the named-CF provider (TBD).
 *
 * ## cloudflared discovery
 *
 * Detected on PATH at start time. Missing → throw with a pointer to
 * the install instructions. We deliberately don't bundle binaries —
 * keeps the OSS package free of platform-specific blobs and defers the
 * "which version" maintenance tax.
 */

import { spawn, type ChildProcess } from "node:child_process"
import { promisify } from "node:util"
import { execFile } from "node:child_process"
import { mkdir, writeFile, rm } from "node:fs/promises"
import { join } from "node:path"
import { randomBytes } from "node:crypto"

import type {
  ProviderStartOptions,
  ProviderStartResult,
  RemoteProvider,
} from "../remote-controller.js"

const execFileAsync = promisify(execFile)

const URL_REGEX = /https:\/\/[a-z0-9-]+\.trycloudflare\.com/i

const STARTUP_TIMEOUT_MS = 30_000

export function quickTunnelProvider(): RemoteProvider {
  let child: ChildProcess | null = null
  let configPath: string | null = null

  return {
    id: "quick",
    async start(opts: ProviderStartOptions): Promise<ProviderStartResult> {
      await assertCloudflaredOnPath()
      const targetUrl = `http://${opts.target.host}:${opts.target.port}`

      // Per-tunnel sentinel config — the only reason it exists is to
      // override `~/.cloudflared/config.yml` so its ingress rules can't
      // shadow our inline `--url` rule. We deliberately do NOT include
      // an `ingress:` block here: quick-tunnel mode treats `--url` as
      // the routing source of truth, and a stray top-level `ingress:`
      // would fight it. Random suffix avoids collisions when dev
      // restarts overlap.
      const id = randomBytes(4).toString("hex")
      const dir = join(opts.workspace, ".agentproto")
      await mkdir(dir, { recursive: true })
      configPath = join(dir, `cloudflared-${id}.yml`)
      const configBody = [
        `# generated by agentproto-runtime — sentinel only`,
        `# overrides ~/.cloudflared/config.yml so its ingress rules`,
        `# don't shadow the inline --url rule. Safe to delete when the`,
        `# tunnel is down.`,
        `no-autoupdate: true`,
        `loglevel: debug`,
        ``,
      ].join("\n")
      await writeFile(configPath, configBody, "utf8")
      const proc = spawn(
        "cloudflared",
        ["tunnel", "--config", configPath, "--url", targetUrl],
        { stdio: ["ignore", "pipe", "pipe"], shell: false },
      )
      child = proc

      const url = await new Promise<string>((resolve, reject) => {
        let settled = false
        const timer = setTimeout(() => {
          if (settled) return
          settled = true
          try {
            proc.kill("SIGTERM")
          } catch {
            /* noop */
          }
          reject(
            new Error(
              `cloudflared did not emit a public URL within ${STARTUP_TIMEOUT_MS / 1000}s`,
            ),
          )
        }, STARTUP_TIMEOUT_MS)

        const onData = (chunk: Buffer) => {
          const text = chunk.toString("utf8")
          for (const line of text.split(/\r?\n/)) {
            if (line.length > 0) opts.onLog?.(`[cloudflared] ${line}`)
          }
          if (settled) return
          const match = text.match(URL_REGEX)
          if (match) {
            settled = true
            clearTimeout(timer)
            resolve(match[0])
          }
        }
        // cloudflared writes the URL to stderr (it reserves stdout for
        // proxied traffic / structured output in some modes). Watch
        // both for safety.
        proc.stderr?.on("data", onData)
        proc.stdout?.on("data", onData)

        proc.once("error", err => {
          if (settled) return
          settled = true
          clearTimeout(timer)
          reject(err)
        })
        proc.once("exit", (code, signal) => {
          if (settled) return
          settled = true
          clearTimeout(timer)
          reject(
            new Error(
              `cloudflared exited before emitting a URL (code=${code}, signal=${signal})`,
            ),
          )
        })
      })

      // Detach the resolver listener (we already captured the URL); leave
      // the log-forwarder attached so the gateway's RuntimeEvents stream
      // sees ongoing tunnel chatter.
      proc.once("exit", (code, signal) => {
        opts.onLog?.(
          `[cloudflared] exited (code=${code ?? "?"} signal=${signal ?? "-"})`,
        )
      })

      return { publicUrl: url, pid: proc.pid ?? null }
    },

    async stop(): Promise<void> {
      const proc = child
      const cfg = configPath
      child = null
      configPath = null
      // Best-effort cleanup of the sentinel config — losing it means a
      // stale `.agentproto/cloudflared-<id>.yml` file, no functional
      // impact. We do this even if the proc never started.
      if (cfg) {
        try {
          await rm(cfg, { force: true })
        } catch {
          /* noop */
        }
      }
      if (!proc || proc.exitCode !== null) return
      proc.kill("SIGTERM")
      // Hard-kill backstop after 3s if cloudflared ignores SIGTERM.
      const timer = setTimeout(() => {
        try {
          proc.kill("SIGKILL")
        } catch {
          /* noop */
        }
      }, 3_000)
      timer.unref()
      await new Promise<void>(resolve => {
        if (proc.exitCode !== null) {
          clearTimeout(timer)
          resolve()
          return
        }
        proc.once("exit", () => {
          clearTimeout(timer)
          resolve()
        })
      })
    },
  }
}

async function assertCloudflaredOnPath(): Promise<void> {
  try {
    await execFileAsync("cloudflared", ["--version"], { timeout: 3_000 })
  } catch {
    throw new Error(
      "cloudflared not found on PATH. Install it first:\n" +
        "  macOS:    brew install cloudflared\n" +
        "  Linux:    https://pkg.cloudflare.com/index.html\n" +
        "  Windows:  winget install --id Cloudflare.cloudflared\n" +
        "Or download a prebuilt binary from https://github.com/cloudflare/cloudflared/releases.",
    )
  }
}
