/**
 * Quick Cloudflare Tunnel provider — zero-credential variant.
 *
 * Spawns `cloudflared tunnel --config <ours>` against an isolated
 * config file we write per-tunnel into the workspace, parses the
 * assigned `*.trycloudflare.com` URL out of cloudflared's stderr.
 * No CF account, no API token, no DNS records. Trade-off: URL is
 * ephemeral (different each run) and there's no Cloudflare Access
 * gating — auth happens at the upstream (gateway bearer token, or
 * whatever the tunneled service does for itself).
 *
 * ## Why we don't use `--url`
 *
 * `cloudflared --url http://...` synthesises an inline ingress block
 * but ALSO merges anything from `~/.cloudflared/config.yml`. If a user
 * has prior named-tunnel config there, hostname-specific rules can
 * shadow the inline rule and every request falls through to the
 * built-in `http_status:404` catch-all (the symptom: cloudflared logs
 * `ingressRule=2 originService=http_status:404` for every request,
 * origin never sees traffic). Writing our own config and passing it
 * via `--config` is hermetic — `~/.cloudflared/config.yml` is ignored
 * entirely, so the URL-forward rule always wins.
 *
 * Use this for: ad-hoc demos, "let me try this from another machine
 * for 10 minutes", iterating on the remote-MCP UX before committing
 * to a domain.
 *
 * For: persistent URLs / SSO gating, use the named-CF provider (TBD).
 *
 * ## cloudflared discovery
 *
 * Detected on PATH at start time. Missing → throw with a pointer to
 * the install instructions. We deliberately don't bundle binaries —
 * keeps the OSS package free of platform-specific blobs and defers the
 * "which version" maintenance tax.
 */

import type { ChildProcess } from "node:child_process"
import { promisify } from "node:util"
import { execFile } from "node:child_process"
import { mkdir, writeFile, rm } from "node:fs/promises"
import { join } from "node:path"
import { randomBytes } from "node:crypto"

import { spawnCloudflaredUntil } from "./cloudflared-spawn.js"
import type {
  ProviderStartOptions,
  ProviderStartResult,
  RemoteProvider,
  TunnelProviderHandle,
} from "./types.js"

const execFileAsync = promisify(execFile)

const URL_REGEX = /https:\/\/[a-z0-9-]+\.trycloudflare\.com/i

const STARTUP_TIMEOUT_MS = 30_000

/** Adapter-kit slug for the quick provider (catalog key). */
export const CLOUDFLARE_QUICK_SLUG = "cloudflare-quick"

/** Quick tunnels need no credentials and offer no stability guarantees. */
export const QUICK_CAPABILITIES = {
  stableUrl: false,
  autostart: false,
  customDomain: false,
  requiresAuth: false,
  hasApi: false,
} as const

export function quickTunnelProvider(): RemoteProvider & TunnelProviderHandle {
  let child: ChildProcess | null = null
  let configPath: string | null = null
  let logFilePath: string | null = null
  let stopLogTail: (() => void) | null = null

  return {
    id: "quick",
    // ── adapter-kit handle surface ──────────────────────────────────
    slug: CLOUDFLARE_QUICK_SLUG,
    name: "Cloudflare Quick Tunnel",
    // In-process provider — no npm package version to report.
    version: "builtin",
    description:
      "Zero-credential Cloudflare tunnel. Ephemeral *.trycloudflare.com URL, fresh each run.",
    requiresSetup: false,
    capabilities: { ...QUICK_CAPABILITIES },
    async check(): Promise<boolean> {
      return cloudflaredOnPath()
    },
    async start(opts: ProviderStartOptions): Promise<ProviderStartResult> {
      await assertCloudflaredOnPath()
      const targetUrl = `http://${opts.target.host}:${opts.target.port}`

      // Per-tunnel sentinel config — the only reason it exists is to
      // override `~/.cloudflared/config.yml` so its ingress rules can't
      // shadow our inline `--url` rule. We deliberately do NOT include
      // an `ingress:` block here: quick-tunnel mode treats `--url` as
      // the routing source of truth, and a stray top-level `ingress:`
      // would fight it. Random suffix avoids collisions when dev
      // restarts overlap.
      const id = randomBytes(4).toString("hex")
      const dir = join(opts.workspace, ".agentproto")
      await mkdir(dir, { recursive: true })
      configPath = join(dir, `cloudflared-${id}.yml`)
      const configBody = [
        `# generated by agentproto-runtime — sentinel only`,
        `# overrides ~/.cloudflared/config.yml so its ingress rules`,
        `# don't shadow the inline --url rule. Safe to delete when the`,
        `# tunnel is down.`,
        `no-autoupdate: true`,
        `loglevel: debug`,
        ``,
      ].join("\n")
      await writeFile(configPath, configBody, "utf8")

      // cloudflared's stdout+stderr are redirected to this file rather than
      // a pipe — see cloudflared-spawn.ts for why (stdio back-pressure
      // wedges the tunnel when spawned under a busy host event loop).
      const logPath = join(dir, `cloudflared-${id}.log`)
      logFilePath = logPath

      const { proc, match, stopTail } = await spawnCloudflaredUntil(
        ["tunnel", "--config", configPath, "--url", targetUrl],
        {
          logPath,
          readyRegex: URL_REGEX,
          timeoutMs: STARTUP_TIMEOUT_MS,
          timeoutMessage: `cloudflared did not emit a public URL within ${STARTUP_TIMEOUT_MS / 1000}s`,
          onLog: opts.onLog,
        },
      )
      child = proc
      stopLogTail = stopTail

      proc.once("exit", (code, signal) => {
        opts.onLog?.(
          `[cloudflared] exited (code=${code ?? "?"} signal=${signal ?? "-"})`,
        )
      })

      return { publicUrl: match, pid: proc.pid ?? null }
    },

    async stop(): Promise<void> {
      const proc = child
      const cfg = configPath
      const log = logFilePath
      const stopTail = stopLogTail
      child = null
      configPath = null
      logFilePath = null
      stopLogTail = null
      // Stop the background log-forwarder before killing cloudflared.
      stopTail?.()
      // Best-effort cleanup of the sentinel config + log file — losing them
      // means stale `.agentproto/cloudflared-<id>.{yml,log}` files, no
      // functional impact. We do this even if the proc never started.
      if (cfg) {
        try {
          await rm(cfg, { force: true })
        } catch {
          /* noop */
        }
      }
      if (log) {
        try {
          await rm(log, { force: true })
        } catch {
          /* noop */
        }
      }
      if (!proc || proc.exitCode !== null) return
      proc.kill("SIGTERM")
      // Hard-kill backstop after 3s if cloudflared ignores SIGTERM.
      const timer = setTimeout(() => {
        try {
          proc.kill("SIGKILL")
        } catch {
          /* noop */
        }
      }, 3_000)
      timer.unref()
      await new Promise<void>(resolve => {
        if (proc.exitCode !== null) {
          clearTimeout(timer)
          resolve()
          return
        }
        proc.once("exit", () => {
          clearTimeout(timer)
          resolve()
        })
      })
    },
  }
}

/**
 * Non-throwing variant for the adapter-kit `check()` health probe — true
 * when `cloudflared` is reachable on PATH. NOT called during listing (the
 * kit derives status from resolvability + creds, per OQ-5); reserved for
 * on-demand health checks.
 */
async function cloudflaredOnPath(): Promise<boolean> {
  try {
    await execFileAsync("cloudflared", ["--version"], { timeout: 3_000 })
    return true
  } catch {
    return false
  }
}

async function assertCloudflaredOnPath(): Promise<void> {
  try {
    await execFileAsync("cloudflared", ["--version"], { timeout: 3_000 })
  } catch {
    throw new Error(
      "cloudflared not found on PATH. Install it first:\n" +
        "  macOS:    brew install cloudflared\n" +
        "  Linux:    https://pkg.cloudflare.com/index.html\n" +
        "  Windows:  winget install --id Cloudflare.cloudflared\n" +
        "Or download a prebuilt binary from https://github.com/cloudflare/cloudflared/releases.",
    )
  }
}
