import { z } from "zod"

import { defineGenerator, type GeneratedFiles, type GeneratorContext } from "../types.js"

/**
 * PINNED source. The HuggingFace router `/v1/models` payload lists every
 * model the router knows about, each carrying a per-model `providers[]`
 * array — one entry per inference provider currently serving it. We never
 * fetch it at build or test time — only behind `--refresh`, which writes
 * `snapshots/llm-huggingface.json` so the next offline run is deterministic.
 * No auth required — the listing endpoint returns HTTP 200 unauthenticated
 * (verified 2026-07-18).
 */
const HUGGINGFACE_MODELS_URL = "https://router.huggingface.co/v1/models"

/** Repo-relative drop-in target for {@link @agentproto/model-catalog}. */
const OUTPUT_PATH = "packages/model-catalog/src/llm/huggingface-routes.generated.ts"

// ── Source schema ────────────────────────────────────────────────────────
// Every per-provider field except `provider`/`status` is optional — some
// entries are sparse (provider+status only). `pricing.input`/`pricing.output`
// are USD-PER-1M-TOKENS NUMBERS (unlike OpenRouter's per-token strings),
// already at the scale LLMPricing expects — no ×1e6 conversion needed.
// passthrough() keeps unread live fields (owned_by, architecture, is_free,
// throughput, …) forward-compatible without a regenerate — we only read
// what we model.

const HFProviderSchema = z
  .object({
    provider: z.string(),
    status: z.string(),
    context_length: z.number().optional(),
    pricing: z
      .object({
        input: z.number().optional(),
        output: z.number().optional(),
      })
      .optional(),
    supports_tools: z.boolean().optional(),
    supports_structured_output: z.boolean().optional(),
  })
  .passthrough()

const HFModelSchema = z
  .object({
    id: z.string(),
    providers: z.array(HFProviderSchema).optional(),
  })
  .passthrough()

const SnapshotSchema = z.object({
  data: z.array(HFModelSchema),
})

// ── Output shape (drop-in for model-catalog's route-identity resolver) ────

interface HuggingFaceRouteProviderEntry {
  provider: string
  status: string
  contextLength?: number
  inputPer1M?: number
  outputPer1M?: number
  supportsTools?: boolean
  supportsStructuredOutput?: boolean
}

interface HuggingFaceRouteEntry {
  wireId: string
  providers: HuggingFaceRouteProviderEntry[]
}

// ── Number helpers ──────────────────────────────────────────────────────

/** Round to 4 decimal places, killing binary-float noise from the source payload. */
function round4(n: number): number {
  return Math.round(n * 10_000) / 10_000
}

// ── Serialization ────────────────────────────────────────────────────────

function serializeProvider(p: HuggingFaceRouteProviderEntry): string {
  const fields: string[] = [
    `provider: ${JSON.stringify(p.provider)}`,
    `status: ${JSON.stringify(p.status)}`,
  ]
  if (p.contextLength !== undefined) fields.push(`contextLength: ${p.contextLength}`)
  if (p.inputPer1M !== undefined) fields.push(`inputPer1M: ${p.inputPer1M}`)
  if (p.outputPer1M !== undefined) fields.push(`outputPer1M: ${p.outputPer1M}`)
  if (p.supportsTools !== undefined) fields.push(`supportsTools: ${p.supportsTools}`)
  if (p.supportsStructuredOutput !== undefined) {
    fields.push(`supportsStructuredOutput: ${p.supportsStructuredOutput}`)
  }
  return `      {\n        ${fields.join(",\n        ")},\n      }`
}

function serializeEntry(id: string, e: HuggingFaceRouteEntry): string {
  const providerLines = e.providers.map(serializeProvider).join(",\n")
  return [
    `  ${JSON.stringify(id)}: {`,
    `    wireId: ${JSON.stringify(e.wireId)},`,
    `    providers: [`,
    providerLines,
    `    ],`,
    `  },`,
  ].join("\n")
}

function serializeFile(entries: Record<string, HuggingFaceRouteEntry>): string {
  const ids = Object.keys(entries).sort()

  const lines: string[] = [
    "// AUTO-GENERATED by @agentproto/catalog-sync (llm:huggingface).",
    "// Do not edit by hand — re-run `pnpm --filter @agentproto/catalog-sync generate`.",
    `// Source: ${HUGGINGFACE_MODELS_URL}`,
    "// Per-model LIVE inference providers from the HuggingFace router. HF wire",
    "// ids are case-sensitive and preserved verbatim. Provider entries are",
    "// SPARSE on some models — every field below except provider/status is",
    "// optional and emitted only when the upstream response carries it. Only",
    '// providers with status === "live" are kept; models with zero live',
    "// providers are skipped. inputPer1M/outputPer1M are USD per 1M tokens",
    "// (HuggingFace router convention — already at that scale, unlike",
    "// OpenRouter's per-token strings).",
    "",
    "export interface HuggingFaceRouteProvider {",
    "  provider: string",
    "  status: string",
    "  contextLength?: number",
    "  inputPer1M?: number",
    "  outputPer1M?: number",
    "  supportsTools?: boolean",
    "  supportsStructuredOutput?: boolean",
    "}",
    "",
    "export interface HuggingFaceRoute {",
    "  wireId: string",
    "  providers: HuggingFaceRouteProvider[]",
    "}",
    "",
    "export const HUGGINGFACE_ROUTES: Record<string, HuggingFaceRoute> = {",
  ]
  for (const id of ids) {
    lines.push(serializeEntry(id, entries[id]!))
  }
  lines.push("}")
  lines.push("")
  return lines.join("\n")
}

// ── Generator ───────────────────────────────────────────────────────────

async function generate(ctx: GeneratorContext): Promise<GeneratedFiles> {
  const src = sources[0]
  if (!src) throw new Error("llm:huggingface: no source configured")
  const parsed = SnapshotSchema.parse(await ctx.fetchSource(src))

  const entries: Record<string, HuggingFaceRouteEntry> = {}
  for (const model of parsed.data) {
    const liveProviders = (model.providers ?? []).filter((p) => p.status === "live")
    if (liveProviders.length === 0) continue

    const providers: HuggingFaceRouteProviderEntry[] = liveProviders
      .map((p) => {
        const entry: HuggingFaceRouteProviderEntry = {
          provider: p.provider,
          status: p.status,
        }
        if (p.context_length !== undefined) entry.contextLength = p.context_length
        if (p.pricing?.input !== undefined) entry.inputPer1M = round4(p.pricing.input)
        if (p.pricing?.output !== undefined) entry.outputPer1M = round4(p.pricing.output)
        if (p.supports_tools !== undefined) entry.supportsTools = p.supports_tools
        if (p.supports_structured_output !== undefined) {
          entry.supportsStructuredOutput = p.supports_structured_output
        }
        return entry
      })
      .sort((a, b) => a.provider.localeCompare(b.provider))

    entries[model.id] = { wireId: model.id, providers }
  }

  return { [OUTPUT_PATH]: serializeFile(entries) }
}

const sources = [
  {
    id: "llm-huggingface",
    url: HUGGINGFACE_MODELS_URL,
  },
]

export const llmHuggingfaceGenerator = defineGenerator({
  name: "llm:huggingface",
  modality: "llm",
  sources,
  generate,
})
