import { z } from "zod"

import { defineGenerator, type CatalogSource, type GeneratedFiles, type GeneratorContext } from "../types.js"

/**
 * Context window (max input tokens) + max output tokens, live per model id,
 * for the four providers that publish a machine-readable models-list with
 * this data: Anthropic, Groq, xAI, Moonshot. This is NOT pricing — Anthropic's
 * `/v1/models` carries no price at all, and Groq/xAI pricing units need
 * separate verification before they're trusted for billing; see
 * `LLM_PRICING_CATALOG` / `OPENROUTER_ROUTES` in `catalog.ts` for that.
 *
 * ZAI/Zhipu and OpenAI are deliberately excluded: ZAI's `/v4/models` list
 * returns bare `{id, owned_by, created}` with no context field, and OpenAI
 * has no stable models-list endpoint at all (see `sources/openai.ts`) — both
 * stay hand-maintained until (if ever) they publish one.
 */

/** Repo-relative drop-in target for {@link @agentproto/model-catalog}. */
const OUTPUT_PATH = "packages/model-catalog/src/llm/context-windows.generated.ts"

// ── Output shape (mirrors ContextWindowEntry in model-catalog's catalog.ts) ──

interface ContextWindowEntry {
  contextWindow: number
  maxOutput?: number
  displayName?: string
  provider: "anthropic" | "groq" | "xai" | "moonshot"
}

// ── Source schemas ───────────────────────────────────────────────────────
// Each provider's models-list shape, verified against the live payload
// (2026-07-16). `passthrough()` keeps unrelated fields forward-compatible.

const AnthropicModelSchema = z
  .object({
    id: z.string(),
    display_name: z.string().optional(),
    max_input_tokens: z.number().optional(),
    max_tokens: z.number().optional(),
  })
  .passthrough()
const AnthropicSnapshotSchema = z.object({ data: z.array(AnthropicModelSchema) })

const GroqModelSchema = z
  .object({
    id: z.string(),
    context_window: z.number().optional(),
    max_completion_tokens: z.number().optional(),
  })
  .passthrough()
const GroqSnapshotSchema = z.object({ data: z.array(GroqModelSchema) })

// xAI's `context_length` is `null` for non-text models (e.g. grok-imagine-video).
const XaiModelSchema = z
  .object({
    id: z.string(),
    context_length: z.number().nullable().optional(),
  })
  .passthrough()
const XaiSnapshotSchema = z.object({ data: z.array(XaiModelSchema) })

const MoonshotModelSchema = z
  .object({
    id: z.string(),
    context_length: z.number().optional(),
  })
  .passthrough()
const MoonshotSnapshotSchema = z.object({ data: z.array(MoonshotModelSchema) })

// ── Serialization ────────────────────────────────────────────────────────

function serializeEntry(e: ContextWindowEntry): string {
  const fields: string[] = [`contextWindow: ${e.contextWindow}`]
  if (e.maxOutput !== undefined) fields.push(`maxOutput: ${e.maxOutput}`)
  if (e.displayName !== undefined) fields.push(`displayName: ${JSON.stringify(e.displayName)}`)
  fields.push(`provider: ${JSON.stringify(e.provider)}`)
  return `{ ${fields.join(", ")} }`
}

function serializeFile(entries: Record<string, ContextWindowEntry>): string {
  const ids = Object.keys(entries).sort()
  const lines: string[] = [
    "// AUTO-GENERATED by @agentproto/catalog-sync (llm:context-windows).",
    "// Do not edit by hand — re-run `pnpm --filter @agentproto/catalog-sync generate --refresh`.",
    "// Sources: api.anthropic.com/v1/models, api.groq.com/openai/v1/models,",
    "//         api.x.ai/v1/models, api.moonshot.ai/v1/models",
    "// Context window (max input tokens) + max output tokens per live model id.",
    "// NOT pricing — see LLM_PRICING_CATALOG / OPENROUTER_ROUTES in catalog.ts.",
    "",
    "export interface ContextWindowEntry {",
    "  contextWindow: number",
    "  maxOutput?: number",
    "  displayName?: string",
    '  provider: "anthropic" | "groq" | "xai" | "moonshot"',
    "}",
    "",
    "export const CONTEXT_WINDOWS: Record<string, ContextWindowEntry> = {",
  ]
  for (const id of ids) {
    lines.push(`  ${JSON.stringify(id)}: ${serializeEntry(entries[id]!)},`)
  }
  lines.push("}")
  lines.push("")
  return lines.join("\n")
}

// ── Generator ───────────────────────────────────────────────────────────

async function generate(ctx: GeneratorContext): Promise<GeneratedFiles> {
  const entries: Record<string, ContextWindowEntry> = {}

  const anthropicSrc = sources.find(s => s.id === "llm-anthropic")
  if (anthropicSrc) {
    const parsed = AnthropicSnapshotSchema.parse(await ctx.fetchSource(anthropicSrc))
    for (const m of parsed.data) {
      if (!m.max_input_tokens || !m.max_tokens) continue
      entries[m.id] = {
        contextWindow: m.max_input_tokens,
        maxOutput: m.max_tokens,
        ...(m.display_name ? { displayName: m.display_name } : {}),
        provider: "anthropic",
      }
    }
  }

  const groqSrc = sources.find(s => s.id === "llm-groq")
  if (groqSrc) {
    const parsed = GroqSnapshotSchema.parse(await ctx.fetchSource(groqSrc))
    for (const m of parsed.data) {
      if (!m.context_window) continue
      entries[m.id] = {
        contextWindow: m.context_window,
        ...(m.max_completion_tokens ? { maxOutput: m.max_completion_tokens } : {}),
        provider: "groq",
      }
    }
  }

  const xaiSrc = sources.find(s => s.id === "llm-xai")
  if (xaiSrc) {
    const parsed = XaiSnapshotSchema.parse(await ctx.fetchSource(xaiSrc))
    for (const m of parsed.data) {
      if (!m.context_length) continue
      entries[m.id] = { contextWindow: m.context_length, provider: "xai" }
    }
  }

  const moonshotSrc = sources.find(s => s.id === "llm-moonshot")
  if (moonshotSrc) {
    const parsed = MoonshotSnapshotSchema.parse(await ctx.fetchSource(moonshotSrc))
    for (const m of parsed.data) {
      if (!m.context_length) continue
      entries[m.id] = { contextWindow: m.context_length, provider: "moonshot" }
    }
  }

  return { [OUTPUT_PATH]: serializeFile(entries) }
}

const sources: CatalogSource[] = [
  {
    id: "llm-anthropic",
    url: "https://api.anthropic.com/v1/models?limit=1000",
    headers: {
      "x-api-key": "env:ANTHROPIC_API_KEY",
      "anthropic-version": "2023-06-01",
    },
  },
  {
    id: "llm-groq",
    url: "https://api.groq.com/openai/v1/models",
    headers: { Authorization: "Bearer env:GROQ_API_KEY" },
  },
  {
    id: "llm-xai",
    url: "https://api.x.ai/v1/models",
    headers: { Authorization: "Bearer env:XAI_API_KEY" },
  },
  {
    id: "llm-moonshot",
    url: "https://api.moonshot.ai/v1/models",
    headers: { Authorization: "Bearer env:MOONSHOT_API_KEY" },
  },
]

export const llmContextWindowsGenerator = defineGenerator({
  name: "llm:context-windows",
  modality: "llm",
  sources,
  generate,
})
