import { z } from "zod"

import { defineGenerator, type GeneratedFiles, type GeneratorContext } from "../types.js"

/**
 * PINNED source. The OpenRouter `/api/v1/models` payload lists every route
 * the router exposes with per-token USD pricing. We never fetch it at build
 * or test time — only behind `--refresh`, which writes
 * `snapshots/llm-openrouter.json` so the next offline run is deterministic.
 */
const OPENROUTER_MODELS_URL = "https://openrouter.ai/api/v1/models"

/** Repo-relative drop-in target for {@link @agentproto/model-catalog}. */
const OUTPUT_PATH = "packages/model-catalog/src/llm/openrouter-routes.generated.ts"

// ── Source schema ────────────────────────────────────────────────────────
// OpenRouter prices are STRINGS of USD-per-token (e.g. "0.000003" = $3/1M).
// `input_cache_read` / `input_cache_write` are optional and only present for
// models that support prompt caching (Anthropic, etc.). These are the REAL
// OpenRouter field names (verified against the live /v1/models payload) — an
// earlier draft used `cache_read`/`cache_write`, which never matched, so cache
// multipliers were silently always absent. passthrough() keeps the other live
// keys (web_search, image, audio, internal_reasoning, input_cache_write_1h)
// forward-compatible without a regenerate — we only read what we model.

const PricingSchema = z
  .object({
    prompt: z.string().optional(),
    completion: z.string().optional(),
    input_cache_read: z.string().optional(),
    input_cache_write: z.string().optional(),
  })
  .passthrough()

const ModelSchema = z
  .object({
    id: z.string(),
    pricing: PricingSchema.optional(),
  })
  .passthrough()

const SnapshotSchema = z.object({
  data: z.array(ModelSchema),
})

// ── Output shape (mirrors model-catalog's LLMPricing) ────────────────────
// Drop-in for `packages/model-catalog/src/llm/openrouter-routes.generated.ts`.
// Structurally identical to LLMPricing — inputPer1M / outputPer1M in USD per
// 1M tokens, plus cacheReadMultiplier / cacheWriteMultiplier WHEN the source
// carries cache_read / cache_write. The existing committed file omits cache
// fields; this generator emits them when present (per the P3 spec: "plus
// cache fields if the source has them"). Fields are optional on LLMPricing,
// so the output remains drop-in compatible.

interface LLMPricingEntry {
  inputPer1M: number
  outputPer1M: number
  cacheReadMultiplier?: number
  cacheWriteMultiplier?: number
  vendor: string
  provider: "openrouter"
}

// ── Number helpers ──────────────────────────────────────────────────────

/** Round to 6 decimal places, killing binary-float noise from the per-token × 1e6 product. */
function round6(n: number): number {
  return Math.round(n * 1_000_000) / 1_000_000
}

/** Convert a per-token USD string to USD-per-1M-tokens, or undefined if unpriced. */
function per1m(tokenPrice: string | undefined): number | undefined {
  if (tokenPrice === undefined) return undefined
  const n = Number(tokenPrice)
  if (!Number.isFinite(n)) return undefined
  return round6(n * 1_000_000)
}

/** Shortest faithful decimal string (matches existing file: 1, 0.5, 0.7448, 1.25). */
function fmt(n: number): string {
  if (!Number.isFinite(n)) return "0"
  return `${round6(n)}`
}

/** Vendor slug = first segment of the OpenRouter route id (`vendor/model`). */
function vendorOf(id: string): string {
  if (!id.includes("/")) return id
  return id.split("/")[0] ?? id
}

// ── Serialization ────────────────────────────────────────────────────────

function serializeEntry(e: LLMPricingEntry): string {
  const fields: string[] = [
    `inputPer1M: ${fmt(e.inputPer1M)}`,
    `outputPer1M: ${fmt(e.outputPer1M)}`,
  ]
  if (e.cacheReadMultiplier !== undefined) {
    fields.push(`cacheReadMultiplier: ${fmt(e.cacheReadMultiplier)}`)
  }
  if (e.cacheWriteMultiplier !== undefined) {
    fields.push(`cacheWriteMultiplier: ${fmt(e.cacheWriteMultiplier)}`)
  }
  fields.push(`vendor: ${JSON.stringify(e.vendor)}`)
  fields.push(`provider: ${JSON.stringify(e.provider)}`)
  return `{\n    ${fields.join(",\n    ")},\n  }`
}

function serializeFile(entries: Record<string, LLMPricingEntry>): string {
  const ids = Object.keys(entries).sort()
  const providers = Array.from(new Set(ids.map(vendorOf))).sort()

  const lines: string[] = [
    "// AUTO-GENERATED by @agentproto/catalog-sync (llm:openrouter).",
    "// Do not edit by hand — re-run `pnpm --filter @agentproto/catalog-sync generate`.",
    `// Source: ${OPENROUTER_MODELS_URL}`,
    "// Pricing carries provider USD (inputPer1M / outputPer1M) plus cache",
    "// multipliers (cacheReadMultiplier / cacheWriteMultiplier) derived from the",
    "// source's input_cache_read / input_cache_write per-token fields when present.",
    "",
    'import type { LLMPricing } from "./catalog.js"',
    "",
    "export const OPENROUTER_ROUTES: Record<string, LLMPricing> = {",
  ]
  for (const id of ids) {
    lines.push(`  ${JSON.stringify(id)}: ${serializeEntry(entries[id]!)},`)
  }
  lines.push("}")
  lines.push("")
  lines.push("/** Provider slugs treated as OpenRouter routes by the picker. */")
  lines.push("export const OPENROUTER_PROVIDERS: readonly string[] = [")
  for (const p of providers) {
    lines.push(`  ${JSON.stringify(p)},`)
  }
  lines.push("]")
  lines.push("")
  return lines.join("\n")
}

// ── Generator ───────────────────────────────────────────────────────────

async function generate(ctx: GeneratorContext): Promise<GeneratedFiles> {
  const src = sources[0]
  if (!src) throw new Error("llm:openrouter: no source configured")
  const parsed = SnapshotSchema.parse(await ctx.fetchSource(src))

  const entries: Record<string, LLMPricingEntry> = {}
  for (const model of parsed.data) {
    const pricing = model.pricing
    if (!pricing) continue
    const inputPer1M = per1m(pricing.prompt)
    const outputPer1M = per1m(pricing.completion)
    if (inputPer1M === undefined || outputPer1M === undefined) continue
    // Skip unpriced routes (e.g. openrouter/auto, which carries "0" pricing).
    if (inputPer1M === 0 && outputPer1M === 0) continue

    const entry: LLMPricingEntry = {
      inputPer1M,
      outputPer1M,
      vendor: vendorOf(model.id),
      provider: "openrouter",
    }

    const cacheReadPer1M = per1m(pricing.input_cache_read)
    const cacheWritePer1M = per1m(pricing.input_cache_write)
    if (cacheReadPer1M !== undefined && cacheReadPer1M > 0 && inputPer1M > 0) {
      entry.cacheReadMultiplier = round6(cacheReadPer1M / inputPer1M)
    }
    if (cacheWritePer1M !== undefined && cacheWritePer1M > 0 && inputPer1M > 0) {
      entry.cacheWriteMultiplier = round6(cacheWritePer1M / inputPer1M)
    }

    entries[model.id] = entry
  }

  return { [OUTPUT_PATH]: serializeFile(entries) }
}

const sources = [{ id: "llm-openrouter", url: OPENROUTER_MODELS_URL }]

export const llmOpenRouterGenerator = defineGenerator({
  name: "llm:openrouter",
  modality: "llm",
  sources,
  generate,
})
