/**
 * Shared CatalogVoice[] → TS-source serializer for the voice generators.
 *
 * The mapping (raw provider JSON → CatalogVoice) lives in
 * `@agentproto/model-catalog/providers` so build time and runtime share it;
 * this module only turns the mapped voices into a committed `*.generated.ts`.
 * Field emit order is fixed (matches the historical generator output) so the
 * generated file stays diff-stable across runs.
 */

import type { CatalogVoice } from "@agentproto/model-catalog/schema/voice"

function serializeVoice(v: CatalogVoice): string {
  const lines: string[] = ["  {"]
  lines.push(`    catalogId: ${JSON.stringify(v.catalogId)},`)
  lines.push(`    providerVoiceId: ${JSON.stringify(v.providerVoiceId)},`)
  lines.push(`    provider: ${JSON.stringify(v.provider)},`)
  lines.push(`    label: ${JSON.stringify(v.label)},`)
  lines.push(`    description: ${JSON.stringify(v.description)},`)
  lines.push(`    gender: ${JSON.stringify(v.gender)},`)
  lines.push(`    primaryLanguage: ${JSON.stringify(v.primaryLanguage)},`)
  lines.push(
    `    supportedLanguages: [${v.supportedLanguages.map(l => JSON.stringify(l)).join(", ")}],`,
  )
  if (v.quality !== undefined) lines.push(`    quality: ${JSON.stringify(v.quality)},`)
  if (v.featured !== undefined) lines.push(`    featured: ${v.featured},`)
  if (v.samplePath !== undefined) lines.push(`    samplePath: ${JSON.stringify(v.samplePath)},`)
  if (v.age !== undefined) lines.push(`    age: ${JSON.stringify(v.age)},`)
  lines.push("  },")
  return lines.join("\n")
}

/**
 * Render a full generated voice module.
 *
 * @param generatorName e.g. `voice:elevenlabs` (goes in the header comment)
 * @param exportName    e.g. `ELEVENLABS_VOICES`
 * @param voices        mapped voices, in emit order
 */
export function serializeVoiceModule(
  generatorName: string,
  exportName: string,
  voices: readonly CatalogVoice[],
): string {
  const lines: string[] = [
    `// Generated by @agentproto/catalog-sync generator ${generatorName}`,
    "// DO NOT EDIT MANUALLY — regenerate with catalog-sync",
    "",
    'import type { CatalogVoice } from "@agentproto/model-catalog/schema/voice"',
    "",
    `export const ${exportName}: readonly CatalogVoice[] = [`,
  ]
  for (const v of voices) lines.push(serializeVoice(v))
  lines.push("] as const")
  lines.push("")
  return lines.join("\n")
}
