/**
 * voice-elevenlabs generator — reads the ElevenLabs /v1/voices snapshot
 * and emits a CatalogVoice[]-shaped generated TS file.
 *
 * Provider-native ids only; no product-specific aliases.
 * catalogId = elevenlabs-<slug(name)>
 */

import type {
  CatalogGenerator,
  CatalogSource,
  GeneratedFiles,
  GeneratorContext,
} from "../types.js"
import { defineGenerator } from "../types.js"

// ── Voice shape mirrors packages/model-catalog/src/schema/voice.ts ──────
// Fields: catalogId, providerVoiceId, provider, label, description,
//         gender, primaryLanguage, supportedLanguages, samplePath?,
//         age?, quality?, featured?

export interface ElevenLabsRawVoice {
  voice_id: string
  name: string
  category: string
  description: string | null
  labels: Record<string, string>
  preview_url: string | null
}

interface ElevenLabsSnapshot {
  voices: ElevenLabsRawVoice[]
}

const SUPPORTED_LANGUAGES = [
  "en", "fr", "es", "de", "it", "pt", "ja", "ko", "zh",
  "ar", "ru", "tr", "nl", "pl", "sv", "hi",
]

const ACCENT_TO_LANG: Record<string, string> = {
  french: "fr",
  british: "en",
  american: "en",
  australian: "en",
  indian: "en",
  spanish: "es",
  german: "de",
  italian: "it",
  portuguese: "pt",
  japanese: "ja",
  korean: "ko",
  chinese: "zh",
  mandarin: "zh",
  arabic: "ar",
  russian: "ru",
  turkish: "tr",
  dutch: "nl",
  polish: "pl",
  swedish: "sv",
  hindi: "hi",
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

function inferGender(labels: Record<string, string>): "female" | "male" | "neutral" {
  const g = labels.gender?.toLowerCase()
  if (g === "female") return "female"
  if (g === "male") return "male"
  return "neutral"
}

function inferAge(labels: Record<string, string>): "child" | "young" | "adult" | "senior" | undefined {
  const a = labels.age?.toLowerCase()
  if (a === "child") return "child"
  if (a === "young") return "young"
  if (a === "middle_aged" || a === "adult") return "adult"
  if (a === "senior") return "senior"
  return undefined
}

function inferPrimaryLanguage(
  labels: Record<string, string>,
): string {
  const accent = labels.accent?.toLowerCase()
  if (accent && ACCENT_TO_LANG[accent]) return ACCENT_TO_LANG[accent]
  return "en"
}

// Featured voice ids (the curated subset from the model-catalog)
const FEATURED_VOICE_IDS = new Set([
  "O31r762Gb3WFygrEOGh0", // Victoire
  "WeAAwKYcS06VmXw086yZ", // Victoria
  "aQROLel5sQbj1vuIVi6B", // Nicolas
  "JBFqnCBsd6RMkjVDRZzb", // George
  "EXAVITQu4vr4xnSDxMaL", // Sarah
  "onwK4e9ZLuTAKqWW03F9", // Daniel
  "Xb7hH8MSUJpSbSDYk0k2", // Alice
])

function mapVoice(raw: ElevenLabsRawVoice) {
  const catalogId = `elevenlabs-${slugify(raw.name)}`
  return {
    catalogId,
    providerVoiceId: raw.voice_id,
    provider: "elevenlabs" as const,
    label: raw.name,
    description: raw.description ?? raw.name,
    gender: inferGender(raw.labels),
    primaryLanguage: inferPrimaryLanguage(raw.labels),
    supportedLanguages: SUPPORTED_LANGUAGES,
    samplePath: raw.preview_url ?? undefined,
    age: inferAge(raw.labels),
    quality: "premium" as const,
    featured: FEATURED_VOICE_IDS.has(raw.voice_id),
  }
}

// ── Generator ────────────────────────────────────────────────────────────

// `id` MUST match the snapshot filename stem — the framework's
// `ctx.fetchSource` resolves `snapshots/<id>.json` (and is the single,
// dist-safe reader; generators never touch the filesystem themselves).
export const ELEVENLABS_SOURCE: CatalogSource = {
  id: "voice-elevenlabs",
  url: "https://api.elevenlabs.io/v1/voices",
  // Live refresh needs the account key; offline reads ignore this.
  headers: { "xi-api-key": "env:ELEVENLABS_API_KEY" },
}

export const voiceElevenlabs: CatalogGenerator = defineGenerator({
  name: "voice:elevenlabs",
  modality: "voice",
  sources: [ELEVENLABS_SOURCE],

  async generate(ctx: GeneratorContext): Promise<GeneratedFiles> {
    // Snapshot-first (refresh re-fetches) — both handled by the framework.
    const data = (await ctx.fetchSource(ELEVENLABS_SOURCE)) as ElevenLabsSnapshot

    const voices = data.voices.map(mapVoice)

    const lines: string[] = [
      "// Generated by @agentproto/catalog-sync generator voice:elevenlabs",
      "// DO NOT EDIT MANUALLY — regenerate with catalog-sync",
      "",
      "import type { CatalogVoice } from \"@agentproto/model-catalog/schema/voice\"",
      "",
      "export const ELEVENLABS_VOICES: readonly CatalogVoice[] = [",
    ]

    for (const v of voices) {
      const feat = v.featured ? "true" : "false"
      const sample = v.samplePath ? `,"samplePath":"${v.samplePath}"` : ""
      const ageField = v.age ? `,"age":"${v.age}"` : ""
      lines.push(`  {`)
      lines.push(`    catalogId: "${v.catalogId}",`)
      lines.push(`    providerVoiceId: "${v.providerVoiceId}",`)
      lines.push(`    provider: "${v.provider}",`)
      lines.push(`    label: "${v.label}",`)
      lines.push(`    description: ${JSON.stringify(v.description)},`)
      lines.push(`    gender: "${v.gender}",`)
      lines.push(`    primaryLanguage: "${v.primaryLanguage}",`)
      lines.push(`    supportedLanguages: [${SUPPORTED_LANGUAGES.map(l => `"${l}"`).join(", ")}],`)
      lines.push(`    quality: "${v.quality}",`)
      lines.push(`    featured: ${feat},`)
      if (v.samplePath) {
        lines.push(`    samplePath: ${JSON.stringify(v.samplePath)},`)
      }
      if (v.age) {
        lines.push(`    age: "${v.age}",`)
      }
      lines.push(`  },`)
    }

    lines.push("] as const")
    lines.push("")

    const outputPath = "packages/catalog-sync/generated/voice-elevenlabs.generated.ts"
    return { [outputPath]: lines.join("\n") }
  },
})
