/**
 * voice-minimax generator — reads the MiniMax /v1/get_voice snapshot
 * and emits a CatalogVoice[]-shaped generated TS file.
 *
 * Provider-native ids only; no product-specific aliases.
 * catalogId = minimax-<slug(voice_id)>
 */

import type {
  CatalogGenerator,
  CatalogSource,
  GeneratedFiles,
  GeneratorContext,
} from "../types.js"
import { defineGenerator } from "../types.js"

// ── MiniMax snapshot shape ──────────────────────────────────────────────

interface MinimaxSystemVoice {
  voice_id: string
  description: string[]
  voice_name: string
  created_time: string
}

interface MinimaxSnapshot {
  system_voice: MinimaxSystemVoice[]
  base_resp: {
    status_code: number
    status_msg: string
  }
}

const SUPPORTED_LANGUAGES = [
  "en", "fr", "es", "de", "it", "pt", "ja", "ko", "zh",
  "ar", "ru", "tr", "nl", "pl", "sv", "da", "no", "fi",
  "hi", "th", "vi", "id", "ms", "tl", "ro", "hu",
]

const LANGUAGE_PREFIX_MAP: Record<string, string> = {
  French: "fr",
  English: "en",
  Spanish: "es",
  German: "de",
  Japanese: "ja",
  Korean: "ko",
  "Chinese (Mandarin)": "zh",
  Portuguese: "pt",
  Italian: "it",
  Arabic: "ar",
  Russian: "ru",
  Turkish: "tr",
  Dutch: "nl",
  Polish: "pl",
  Swedish: "sv",
  Danish: "da",
  Norwegian: "no",
  Finnish: "fi",
  Hindi: "hi",
  Thai: "th",
  Vietnamese: "vi",
  Indonesian: "id",
  Malay: "ms",
  Tagalog: "tl",
  Romanian: "ro",
  Hungarian: "hu",
}

function extractLanguageFromVoiceId(voiceId: string): string {
  for (const [prefix, lang] of Object.entries(LANGUAGE_PREFIX_MAP)) {
    if (voiceId.startsWith(prefix)) return lang
  }
  return "en"
}

const FEMALE_KEYWORDS = ["female", "woman", "lady", "girl", "heroine", "sweet"]
const MALE_KEYWORDS = ["male", "man", "butler", "gentleman", "narrator", "executive"]

function inferGender(voiceId: string): "female" | "male" | "neutral" {
  const lower = voiceId.toLowerCase()
  if (FEMALE_KEYWORDS.some(k => lower.includes(k))) return "female"
  if (MALE_KEYWORDS.some(k => lower.includes(k))) return "male"
  return "neutral"
}

function inferAge(voiceId: string): "child" | "young" | "adult" | "senior" | undefined {
  const lower = voiceId.toLowerCase()
  if (lower.includes("child")) return "child"
  if (lower.includes("girl") || lower.includes("young")) return "young"
  if (lower.includes("senior")) return "senior"
  return "adult"
}

function slugify(voiceId: string): string {
  return voiceId
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

// All voices currently in the MiniMax snapshot are featured
function isFeatured(_voiceId: string): boolean {
  return true
}

function mapVoice(raw: MinimaxSystemVoice) {
  const catalogId = `minimax-${slugify(raw.voice_id)}`
  return {
    catalogId,
    providerVoiceId: raw.voice_id,
    provider: "minimax" as const,
    label: raw.voice_name,
    description: raw.description[0] ?? raw.voice_name,
    gender: inferGender(raw.voice_id),
    primaryLanguage: extractLanguageFromVoiceId(raw.voice_id),
    supportedLanguages: SUPPORTED_LANGUAGES,
    age: inferAge(raw.voice_id),
    quality: "premium" as const,
    featured: isFeatured(raw.voice_id),
  }
}

// ── Generator ────────────────────────────────────────────────────────────

// `id` MUST match the snapshot filename stem — the framework's
// `ctx.fetchSource` resolves `snapshots/<id>.json` (single dist-safe reader;
// generators never touch the filesystem themselves).
export const MINIMAX_SOURCE: CatalogSource = {
  id: "voice-minimax",
  url: "https://api.minimax.io/v1/get_voice",
  // get_voice is a POST; live refresh needs the account key (Bearer). Without
  // MINIMAX_API_KEY set, the framework reuses the committed snapshot.
  method: "POST",
  headers: {
    Authorization: "Bearer env:MINIMAX_API_KEY",
    "Content-Type": "application/json",
  },
  body: { voice_type: "system" },
}

export const voiceMinimax: CatalogGenerator = defineGenerator({
  name: "voice:minimax",
  modality: "voice",
  sources: [MINIMAX_SOURCE],

  async generate(ctx: GeneratorContext): Promise<GeneratedFiles> {
    // Snapshot-first (refresh re-fetches) — both handled by the framework.
    const data = (await ctx.fetchSource(MINIMAX_SOURCE)) as MinimaxSnapshot

    const voices = data.system_voice.map(mapVoice)

    const lines: string[] = [
      "// Generated by @agentproto/catalog-sync generator voice:minimax",
      "// DO NOT EDIT MANUALLY — regenerate with catalog-sync",
      "",
      "import type { CatalogVoice } from \"@agentproto/model-catalog/schema/voice\"",
      "",
      "export const MINIMAX_VOICES: readonly CatalogVoice[] = [",
    ]

    for (const v of voices) {
      lines.push(`  {`)
      lines.push(`    catalogId: "${v.catalogId}",`)
      lines.push(`    providerVoiceId: ${JSON.stringify(v.providerVoiceId)},`)
      lines.push(`    provider: "${v.provider}",`)
      lines.push(`    label: ${JSON.stringify(v.label)},`)
      lines.push(`    description: ${JSON.stringify(v.description)},`)
      lines.push(`    gender: "${v.gender}",`)
      lines.push(`    primaryLanguage: "${v.primaryLanguage}",`)
      lines.push(`    supportedLanguages: [${SUPPORTED_LANGUAGES.map(l => `"${l}"`).join(", ")}],`)
      lines.push(`    quality: "${v.quality}",`)
      lines.push(`    featured: true,`)
      if (v.age) {
        lines.push(`    age: "${v.age}",`)
      }
      lines.push(`  },`)
    }

    lines.push("] as const")
    lines.push("")

    const outputPath = "packages/catalog-sync/generated/voice-minimax.generated.ts"
    return { [outputPath]: lines.join("\n") }
  },
})
