#!/usr/bin/env bash
# Session snapshot: the 50 most recently active daemon agent sessions, written
# to a markdown file. Data comes from the daemon — never hand-edited.
#
# Usage: ./scripts/sessions-snapshot.sh [out.md] [count]
#   default out: data/sessions-latest.md, default count: 50

set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
app_root="$(dirname "$here")"
out="${1:-$app_root/data/sessions-latest.md}"
count="${2:-50}"
mkdir -p "$(dirname "$out")"

# GET /sessions returns { sessions: [...] } with full descriptors and ignores
# ?limit, so sorting + truncation happen here.
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
curl -sf http://127.0.0.1:18790/sessions -o "$tmp/sessions.json"
curl -sf "http://127.0.0.1:18790/workflows?limit=200" -o "$tmp/workflows.json" || echo '{}' > "$tmp/workflows.json"

node -e '
const fs = require("fs");
const [out, count, dir] = process.argv.slice(1);
const raw = JSON.parse(fs.readFileSync(dir + "/sessions.json", "utf8"));
const wf = JSON.parse(fs.readFileSync(dir + "/workflows.json", "utf8"));
const runs = (Array.isArray(wf) ? wf : wf.items || wf.runs || [])
  .filter((r) => r.workflowId === "session-steward")
  .sort((a, b) => String(b.startedAt).localeCompare(String(a.startedAt)));
const lastRun = runs[0];
const ts = (s) => Date.parse(s.lastActivityAt || s.lastOutputAt || s.startedAt || 0) || 0;
const sessions = raw.sessions
  .filter((s) => s.kind === "agent-cli")
  .sort((a, b) => ts(b) - ts(a))
  .slice(0, Number(count));
const cell = (v) => String(v ?? "").replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
const idle = (s) => {
  const sec = s.secondsSinceLastActivity ?? (Date.now() - ts(s)) / 1000;
  if (sec < 3600) return Math.round(sec / 60) + "m";
  if (sec < 86400) return Math.round(sec / 3600) + "h";
  return Math.round(sec / 86400) + "d";
};
const status = (s) =>
  s.status + (s.busy ? " (busy)" : "") + (s.awaitingInput ? " (awaiting input)" : "");
const flag = (s) =>
  s.wrapupFlag ? s.wrapupFlag.verdict + (s.wrapupFlag.note ? ": " + s.wrapupFlag.note : "") : "";
const outcome = (s) => {
  const o = s.outcome;
  if (!o) return "";
  const t = o.termination;
  return [o.status, t && t.status + (t.reason ? " (" + t.reason + ")" : "")].filter(Boolean).join(" / ");
};
const rows = sessions.map((s) =>
  "| " +
  [
    s.id,
    cell(s.label || s.title),
    s.adapterSlug || "-",
    cell(s.model || s.activeModel || "-"),
    status(s),
    idle(s),
    s.parentSessionId || "",
    cell(flag(s)),
    cell(outcome(s)),
    cell((s.activitySummary?.text || "").slice(0, 100)),
  ].join(" | ") +
  " |",
);
const flagged = sessions.filter((s) => s.wrapupFlag).length;
const md = [
  "# Session snapshot — " + new Date().toISOString(),
  "",
  "Last " + rows.length + " agent sessions by activity (of " + raw.sessions.length +
    " daemon sessions). Steward-flagged: " + flagged + ".",
  "Last steward run: " + (lastRun ? lastRun.runId + " (" + lastRun.status + ", " + lastRun.startedAt + ")" : "none found"),
  "Generated by scripts/sessions-snapshot.sh — do not hand-edit.",
  "",
  "| id | label | adapter | model | status | idle | parent | steward flag | outcome | last summary |",
  "|---|---|---|---|---|---|---|---|---|---|",
  ...rows,
  "",
].join("\n");
fs.writeFileSync(out, md);
console.log("wrote", out, "(" + rows.length + " sessions, " + flagged + " flagged)");
' "$out" "$count" "$tmp"
