/**
 * AIP-6 COMPANY.md frontmatter zod schema.
 *
 * Generated from `resources/aip-6/draft/COMPANY.schema.json` via
 * json-schema-to-zod. Imported by both `define-company.ts` (TS path
 * validation) and `manifest/index.ts` (.md path validation) so every
 * field-level constraint runs in both authoring paths from a single
 * source of truth — re-run scaffold-aip to refresh after spec changes.
 *
 * Cross-field rules (if/then/allOf in JSON Schema) don't translate
 * cleanly and live in `define-company.ts`'s `validate(def)` instead.
 */

import { z } from "zod"

export const companyFrontmatterSchema = z.discriminatedUnion("doctype", [
  z.object({ "schema": z.literal("agentcompanies/v1").describe("Format identifier. MUST be the literal string `agentcompanies/v1`."), "doctype": z.literal("company"), "id": z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$")).min(2).max(64).describe("Slug identifier. Lowercase, digits, dashes. Stable across renames; references use this, never database IDs."), "version": z.string().regex(new RegExp("^\\d+\\.\\d+\\.\\d+(?:[-+][a-zA-Z0-9.-]+)?$")).describe("Spec version of THIS file. Bump on breaking change.").optional(), "name": z.string().min(1).max(200).describe("Human-readable display name."), "description": z.string().max(2000).describe("One-paragraph purpose.").optional(), "tags": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*$"))).default([] as never), "metadata": z.record(z.string(), z.any()).describe("Vendor-specific extensions. Authors stash hints under namespaced keys `metadata.<vendor>.…`; other readers MUST tolerate unknown keys.").default({} as never), "mission": z.string().min(1).max(1000).describe("One-paragraph mission. Read by every operator at boot."), "values": z.array(z.string().max(200)).describe("Short value statements; surfaced in role prompts.").default([] as never), "structure": z.object({ "roles": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$"))).describe("Slugs of roles defined under `roles/<slug>/ROLE.md`.").default([] as never), "objectives": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$"))).describe("Slugs of top-level objectives defined under `objectives/<slug>/OBJECTIVE.md`.").default([] as never), "reports_to": z.record(z.string(), z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$"))).describe("Map of role-slug → role-slug expressing the reporting tree. The key reports to the value. Roles not in the map are top-level.").default({} as never) }).strict().optional(), "imports": z.array(z.any()).describe("External roles or objectives pulled from a registry. Resolved by the adapter at load time.").default([] as never) }).catchall(z.any()),
  z.object({ "schema": z.literal("agentcompanies/v1").describe("Format identifier. MUST be the literal string `agentcompanies/v1`."), "doctype": z.literal("role"), "id": z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$")).min(2).max(64).describe("Slug identifier. Lowercase, digits, dashes. Stable across renames; references use this, never database IDs."), "version": z.string().regex(new RegExp("^\\d+\\.\\d+\\.\\d+(?:[-+][a-zA-Z0-9.-]+)?$")).describe("Spec version of THIS file. Bump on breaking change.").optional(), "name": z.string().min(1).max(200).describe("Human-readable display name."), "description": z.string().max(2000).describe("One-paragraph purpose.").optional(), "tags": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*$"))).default([] as never), "metadata": z.record(z.string(), z.any()).describe("Vendor-specific extensions. Authors stash hints under namespaced keys `metadata.<vendor>.…`; other readers MUST tolerate unknown keys.").default({} as never), "mandate": z.string().min(1).max(2000).describe("One-paragraph statement of what this role is responsible for. Defines the role's bounded autonomy."), "reports_to": z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$")).describe("Slug of the parent role. Omit for top-level roles.").optional(), "scope": z.object({ "owns": z.array(z.string().max(200)).describe("Free-text list of resource classes this role owns (e.g. `outbound-email`, `q3-pipeline`).").default([] as never), "capabilities": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*$"))).describe("Capability slugs the role grants — referenced by AIP-7 governance and AIP-8 operators.").default([] as never) }).strict().optional(), "objectives": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$"))).describe("Slugs of objectives this role pursues. Each MUST resolve to an `objectives/<slug>/OBJECTIVE.md`.").default([] as never), "tools": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$"))).describe("Slugs of AIP-14 tools the role may call. Adapter resolves against the host's tool catalog.").default([] as never), "workflows": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$"))).describe("Slugs of AIP-15 workflows the role may execute.").default([] as never) }).catchall(z.any()),
  z.object({ "schema": z.literal("agentcompanies/v1").describe("Format identifier. MUST be the literal string `agentcompanies/v1`."), "doctype": z.literal("objective"), "id": z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$")).min(2).max(64).describe("Slug identifier. Lowercase, digits, dashes. Stable across renames; references use this, never database IDs."), "version": z.string().regex(new RegExp("^\\d+\\.\\d+\\.\\d+(?:[-+][a-zA-Z0-9.-]+)?$")).describe("Spec version of THIS file. Bump on breaking change.").optional(), "name": z.string().min(1).max(200).describe("Human-readable display name."), "description": z.string().max(2000).describe("One-paragraph purpose.").optional(), "tags": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*$"))).default([] as never), "metadata": z.record(z.string(), z.any()).describe("Vendor-specific extensions. Authors stash hints under namespaced keys `metadata.<vendor>.…`; other readers MUST tolerate unknown keys.").default({} as never), "statement": z.string().min(1).max(2000).describe("One-paragraph statement of the desired outcome."), "owner": z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$")).describe("Slug of the role accountable for this objective.").optional(), "horizon": z.enum(["sprint","quarter","year","ongoing"]).describe("Time horizon. Adapter MAY use this to surface stale objectives.").default("quarter"), "status": z.enum(["proposed","active","paused","achieved","abandoned"]).default("active"), "key_results": z.array(z.object({ "id": z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$")), "statement": z.string().max(500), "target": z.string().max(200).optional(), "progress": z.number().gte(0).lte(1).optional() }).strict()).default([] as never), "parent": z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$")).describe("Slug of the parent objective (for decomposition trees). Omit for top-level objectives.").optional(), "children": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$"))).describe("Slugs of child sub-objectives. Adapter validates the parent/children edges agree.").default([] as never), "depends_on": z.array(z.string().regex(new RegExp("^[a-z][a-z0-9-]*[a-z0-9]$"))).describe("Slugs of objectives this one depends on.").default([] as never) }).catchall(z.any()),
]).describe("Validates the YAML frontmatter portion of any agentcompanies/v1 doctype file. The `doctype` field discriminates between company / role / objective; each branch enforces the doctype-specific shape. Operator doctype is sketched here but the normative definition lives in AIP-8 — only company / role / objective are normative under AIP-6.")

export type CompanyFrontmatter = z.infer<typeof companyFrontmatterSchema>
