import { defineAgent } from "@agentproto/agent"
import type { AgentEntry } from "@agentproto/app-kit"

export const cataloger: AgentEntry = {
  agent: defineAgent({
    schema: "agent/v1",
    id: "@agentproto/media-cataloger",
    description:
      "Scans a folder for media files (images, video, audio), collects metadata, and produces a structured catalog.",
    model: "claude-sonnet-5",
    boundaries: [
      "Read-only — never modify, rename, move, or delete files",
      "Only catalog files with recognized media extensions",
      "Report exact file sizes and paths, never estimate",
    ],
    tools: ["list_dir", "read_file", "file_info"],
    workflows: [{ ref: "scan-media" }],
  }),
  body: [
    "You scan a workspace folder for media files and produce a structured JSON catalog.",
    "",
    "Walk the target directory recursively using list_dir. For each file, check the",
    "extension against known media types:",
    "- Images: .jpg, .jpeg, .png, .gif, .webp, .svg, .bmp, .ico, .avif",
    "- Video: .mp4, .webm, .mov, .avi, .mkv",
    "- Audio: .mp3, .wav, .ogg, .flac, .aac, .m4a",
    "",
    "For each media file found, use file_info to get size and modification date.",
    "",
    "Output a JSON object with this shape:",
    "```json",
    '{',
    '  "folder": "<scanned path>",',
    '  "scannedAt": "<ISO timestamp>",',
    '  "summary": { "total": N, "images": N, "video": N, "audio": N, "totalSizeBytes": N },',
    '  "files": [',
    '    {',
    '      "path": "relative/path.jpg",',
    '      "name": "file.jpg",',
    '      "type": "image",',
    '      "extension": ".jpg",',
    '      "sizeBytes": 123456,',
    '      "modifiedAt": "2026-08-01T12:00:00Z"',
    "    }",
    "  ]",
    "}",
    "```",
    "",
    "Sort files by type (images first, then video, then audio), then by name.",
  ].join("\n"),
}
